kind: Deployment
apiVersion: apps/v1
metadata:
  name: unifi
  namespace: networking
  labels:
    app: unifi
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      securityContext:
        fsGroup: 568
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:8.0.7
          volumeMounts:
            - mountPath: /config
              name: unifi-config
          env:
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
            - name: TZ
              value: "America/Toronto"
            - name: MONGO_USER
              value: "unifi"
            - name: MONGO_PASS
              value: "ElectronicOstensiblyHeartStride"
            - name: MONGO_HOST
              value: "mongodb.database.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "unifi"
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: networking
spec:
  type: LoadBalancer
  selector:
    app: unifi
  ports:
    - name: https
      targetPort: 8443
      port: 8443
    - name: stun
      targetPort: 3478
      port: 3478
      protocol: UDP
    - name: ap-discovery
      targetPort: 10001
      port: 10001
      protocol: UDP
    - name: comms
      targetPort: 8080
      port: 8080
