---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  namespace: default
  labels:
    app: jellyfin
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      initContainers:
        - name: jellyfin-restore
          image: untouchedwagons/simple-restore:1.0.4
          volumeMounts:
            - mountPath: /data
              name: jellyfin-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/jellyfin"
            - name: BACKUP_BASE_NAME
              value: "jellyfin"
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.8.12
          resources:
            limits:
              memory: 3072Mi
              cpu: "2"
              nvidia.com/gpu: "1"
            requests:
              memory: 1024Mi
              cpu: "1"
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /config/transcodes
              name: jellyfin-transcode
            - mountPath: /mnt/data/Videos
              name: videos
            - mountPath: /mnt/data/Music
              name: music
        - name: backup
          image: untouchedwagons/simple-backup:1.0.5
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /data
              name: jellyfin-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/jellyfin"
            - name: BACKUP_BASE_NAME
              value: "jellyfin"
            - name: BACKUP_RETENTION
              value: "24"
            - name: BACKUP_FREQUENCY
              value: "0 */8 * * *"
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-transcode
          emptyDir:
            medium: Memory
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
        - name: videos
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Videos
        - name: music
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Music
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      targetPort: 8096
      port: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: jellyfin.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              number: 8096
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal
