---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jellyfin-vol-restore
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: restore
        image: untouchedwagons/simple-restore:1.0.2
        volumeMounts:
          - mountPath: /data
            name: jellyfin-config
          - mountPath: /backups
            name: backups
        env:
          - name: BACKUP_APPEND_DIRECTORY
            value: "/kubernetes/production/jellyfin"
          - name: BACKUP_BASE_NAME
            value: "jellyfin"
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
      restartPolicy: Never