---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi
