---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.3/charts/library/common/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: codeproject/ai-server
          tag: cpu-2.6.5
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            type: HTTP
            path: /
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 32168

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: local-path
    size: 3Gi
    advancedMounts:
      main: 
        main:
          - path: /etc/codeproject/ai
            subPath: data
          - path: /app/modules
            subPath: modules
  usb:
    type: hostPath
    hostPath: /dev
    hostPathType: Directory
    globalMounts:
      - path: /dev