---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
  namespace: servarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 568
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:15.5
          env:
            - name: INIT_POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: INIT_POSTGRES_USER
              value: "prowlarr"
            - name: INIT_POSTGRES_PASS
              value: "CulpableRadianceCavityDespotic"
            - name: INIT_POSTGRES_DBNAME
              value: "prowlarr-main prowlarr-logs"
            - name: INIT_POSTGRES_SUPER_PASS
              value: "TrembleBulwarkBeautifulGossip"
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr:1.11.4.4173
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          env:
            - name: PROWLARR__API_KEY
              value: "fa88672ddbeb4b5683a009951076bf38"
            - name: PROWLARR__AUTHENTICATION_METHOD
              value: "Forms"
            - name: PROWLARR__AUTHENTICATION_REQUIRED
              value: "DisabledForLocalAddresses"
            - name: PROWLARR__POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: PROWLARR__POSTGRES_MAIN_DB
              value: "prowlarr-main"
            - name: PROWLARR__POSTGRES_LOG_DB
              value: "prowlarr-logs"
            - name: PROWLARR__POSTGRES_USER
              value: "prowlarr"
            - name: PROWLARR__POSTGRES_PASSWORD
              value: "CulpableRadianceCavityDespotic"
          resources:
            limits:
              memory: 256Mi
              cpu: "4"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
          - mountPath: /config
            name: prowlarr-config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: servarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      targetPort: 9696
      port: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: servarr
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: prowlarr.services.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: prowlarr
            port:
              number: 9696
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal-services
