---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
  namespace: servarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 568
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:15.5
          env:
            - name: INIT_POSTGRES_HOST
              value: "postgresql-cluster-rw.database.svc.cluster.local"
            - name: INIT_POSTGRES_USER
              value: "prowlarr"
            - name: INIT_POSTGRES_PASS
              value: "CulpableRadianceCavityDespotic"
            - name: INIT_POSTGRES_DBNAME
              value: "prowlarr-main prowlarr-logs"
            - name: INIT_POSTGRES_SUPER_PASS
              value: "TrembleBulwarkBeautifulGossip"
        - name: restore
          image: untouchedwagons/simple-restore:1.0.4
          volumeMounts:
            - mountPath: /data
              name: prowlarr-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/prowlarr"
            - name: BACKUP_BASE_NAME
              value: "prowlarr"
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr:1.15.0.4361
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          env:
            - name: PROWLARR__API_KEY
              value: "fa88672ddbeb4b5683a009951076bf38"
            - name: PROWLARR__AUTHENTICATION_METHOD
              value: "Forms"
            - name: PROWLARR__AUTHENTICATION_REQUIRED
              value: "DisabledForLocalAddresses"
            - name: PROWLARR__POSTGRES_HOST
              value: "postgresql-cluster-rw.database.svc.cluster.local"
            - name: PROWLARR__POSTGRES_MAIN_DB
              value: "prowlarr-main"
            - name: PROWLARR__POSTGRES_LOG_DB
              value: "prowlarr-logs"
            - name: PROWLARR__POSTGRES_USER
              value: "prowlarr"
            - name: PROWLARR__POSTGRES_PASSWORD
              value: "CulpableRadianceCavityDespotic"
          resources:
            limits:
              memory: 256Mi
              cpu: "4"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
          - mountPath: /config
            name: prowlarr-config
        - name: backup
          image: untouchedwagons/simple-backup:1.0.5
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /data
              name: prowlarr-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/prowlarr"
            - name: BACKUP_BASE_NAME
              value: "prowlarr"
            - name: BACKUP_RETENTION
              value: "24"
            - name: BACKUP_FREQUENCY
              value: "0 0 * * *"
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: backups
          nfs:
            server: 192.168.35.30
            path: /mnt/tank/Media/Backups
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: servarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      targetPort: 9696
      port: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: servarr
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Multimedia
    gethomepage.dev/icon: prowlarr.png
    gethomepage.dev/name: Prowlarr
    gethomepage.dev/widget.type: "prowlarr"
    gethomepage.dev/widget.url: "https://prowlarr.services.untouchedwagons.com"
    gethomepage.dev/widget.key: "fa88672ddbeb4b5683a009951076bf38"
spec:
  rules:
  - host: prowlarr.services.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: prowlarr
            port:
              number: 9696
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-services
