---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    fsGroup: 568
  annotations:
    enable.version-checker.io/main: "true"
    use-sha.version-checker.io/main: "false"

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/prowlarr
          tag: 1.17.2.4511
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          PROWLARR__API_KEY: "fa88672ddbeb4b5683a009951076bf38"
          PROWLARR__AUTHENTICATION_METHOD: "Forms"
          PROWLARR__AUTHENTICATION_REQUIRED: "DisabledForLocalAddresses"
        resources:
          requests:
            memory: 256Mi
            cpu: "1m"
          limits:
            memory: 1024Mi
            cpu: "1"

service:
  main:
    controller: main
    ports:
      http:
        port: 9696

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Multimedia
      gethomepage.dev/icon: prowlarr.png
      gethomepage.dev/name: Prowlarr
      gethomepage.dev/widget.type: "prowlarr"
      gethomepage.dev/widget.url: "https://prowlarr.services.untouchedwagons.com"
      gethomepage.dev/widget.key: "fa88672ddbeb4b5683a009951076bf38"
    hosts:
      - host: prowlarr.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: prowlarr-config
    advancedMounts:
      main: 
        main:
          - path: /config
        restore:
          - path: /data
