---
creation_rules:
  - path_regex: production/cert-manager/02-cert-manager.yaml
    encrypted_regex: "^(cloudflare-token|email)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/default/qbittorrent/service.yaml
    encrypted_regex: "^(stringData)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/monitoring/prometheus/service.yaml
    encrypted_regex: "^(email_configs)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/networking/ddclient/service.yaml
    encrypted_regex: "^(data)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: testing/cert-manager/02-cert-manager.yaml
    encrypted_regex: "^(data|stringData|email|dnsZones|dnsNames|commonName)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn