---
creation_rules:
  - path_regex: production/cert-manager/02-cert-manager.yaml
    encrypted_regex: "^(cloudflare-token|email)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/default/qbittorrent/values.yaml
    encrypted_regex: "^(WIREGUARD_)"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/monitoring/prometheus/values.yaml
    encrypted_regex: "^(pushover_configs)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/networking/rclone/service.yaml
    encrypted_regex: "^(data|volumeMounts|volumes)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/networking/cloudflared/values.yaml
    encrypted_regex: "^(token)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/networking/ddclient/values.yaml
    encrypted_regex: "^(data)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/networking/msmtpd/service.yaml
    encrypted_regex: "^(value)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/version-checker/version-checker/values.yaml
    encrypted_regex: "^(token)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: production/volsync-system/secrets.yaml
    encrypted_regex: "^(AWS_|RESTIC_)"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
  - path_regex: testing/cert-manager/02-cert-manager.yaml
    encrypted_regex: "^(stringData|email)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn

stores:
  yaml:
    indent: 2