---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    initContainers:
      restore:
        image:
          repository: untouchedwagons/simple-restore
          tag: 1.0.4
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/stash"
          BACKUP_BASE_NAME: "stash"

    containers:
      main:
        image:
          repository: ghcr.io/hotio/stash
          tag:  release-0.25.1
        env:
          TZ: "America/Toronto"
        resources:
          requests:
            memory: 1024Mi
            cpu: "10m"
            gpu.intel.com/i915: "1"
          limits:
            gpu.intel.com/i915: "1"

      backup:
        image:
          repository: untouchedwagons/simple-backup
          tag: 1.0.6
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/stash"
          BACKUP_BASE_NAME: "stash"
          BACKUP_RETENTION: "24"
          BACKUP_FREQUENCY: "0 0 * * *"

defaultPodOptions:
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 9999

ingress:
  main:
    hosts:
      - host: stash.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Multimedia
      gethomepage.dev/icon: stash.png
      gethomepage.dev/name: Stash
      gethomepage.dev/widget.type: "stash"
      gethomepage.dev/widget.url: "https://stash.services.untouchedwagons.com"

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 50Gi
    advancedMounts:
      main: 
        main:
          - path: /config
        backup:
          - path: /data
        restore:
          - path: /data

  nfs-backups:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Backups"
    advancedMounts:
      main: 
        backup:
          - path: /backups
        restore:
          - path: /backups

  nfs-porn:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Porn"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Porn
