apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:q6RcGW9YN+k565QTsV4ZUzE4tPOWEzyyJLiDlG1OxAPXt75WSiC05w==,iv:ne/I6UQRqPVROBXmcxiw+R3a9t71eBOrXRJpL9KihZI=,tag:s81zqdZuwWsK657CFiKCNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTlJwY3hwMHBDOWxJaDhx
            YmlHaEM2dEovQXhGZkRkKy94VUFyelFPaWdnCnl4cS93ZXR5czZMVjYyK3JpRHU0
            Sjg2ck5aOFN1dVVJNTMrZGozVFRySDAKLS0tIGxSZkgyNGdhZWZaYWVkZHkySXNx
            dFZScE1mUkFPVHFmbE5Sb2JDTVM0NlUKSKRN0EnHA4dnghkcCqi7ijxhownfE2PS
            yVjVfQk7MpGeXRlo9Pc8atyhWuKIP9AcxqVhQ5YcMmIoCOhxCC6OxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T19:42:51Z"
    mac: ENC[AES256_GCM,data:9c486pEsWF+1Dr0eYVoLPEyON4ZpugejzPPR8+DqADzp3Op/bayCSLykUY9whfH+mrrGxNkv13cY5nVXLuI4TFgFssCu20nQnIxfJgdTpFiwbA3p+4TIUakf7iSRHiEB6MTTjw0ODBH1dwjHIYBHX0YE4Ez2a7ZMJIZtZtR72F4=,iv:Rq2FUokT5PowH5B8H+HzUNuX0V4GewM0K9Xd+ZOQRnI=,tag:BAJni7gMsJ8g0cenkHbNBg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|email)$
    version: 3.8.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: com-untouchedwagons-testing
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:6egSLleUvimwddpOHqT2GbPZdCWewFh2UA==,iv:CpCGfcx4kJ/3fF6Veb7ywaM+SLCTqakYFHeIcVfRhkA=,tag:3Ec9tIFdy5rNYtRtiP/IAA==,type:str]
        privateKeySecretRef:
            name: com-untouchedwagons-testing
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:ditZ6Q7Gfyd7rfwgwUUqcAShaVCAQVkRXQ==,iv:VuNjCzLWF4/8lEkL+94WbfXER8XsdGC1f2g+Cm9+Cak=,tag:QNdQxEMKm2YPjrrlX1KnUQ==,type:str]
                    apiTokenSecretRef:
                        name: cloudflare-token-secret
                        key: cloudflare-token
              selector:
                dnsZones:
                    - untouchedwagons.com
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTlJwY3hwMHBDOWxJaDhx
            YmlHaEM2dEovQXhGZkRkKy94VUFyelFPaWdnCnl4cS93ZXR5czZMVjYyK3JpRHU0
            Sjg2ck5aOFN1dVVJNTMrZGozVFRySDAKLS0tIGxSZkgyNGdhZWZaYWVkZHkySXNx
            dFZScE1mUkFPVHFmbE5Sb2JDTVM0NlUKSKRN0EnHA4dnghkcCqi7ijxhownfE2PS
            yVjVfQk7MpGeXRlo9Pc8atyhWuKIP9AcxqVhQ5YcMmIoCOhxCC6OxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T19:42:51Z"
    mac: ENC[AES256_GCM,data:9c486pEsWF+1Dr0eYVoLPEyON4ZpugejzPPR8+DqADzp3Op/bayCSLykUY9whfH+mrrGxNkv13cY5nVXLuI4TFgFssCu20nQnIxfJgdTpFiwbA3p+4TIUakf7iSRHiEB6MTTjw0ODBH1dwjHIYBHX0YE4Ez2a7ZMJIZtZtR72F4=,iv:Rq2FUokT5PowH5B8H+HzUNuX0V4GewM0K9Xd+ZOQRnI=,tag:BAJni7gMsJ8g0cenkHbNBg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|email)$
    version: 3.8.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: com-untouchedwagons-testing
    namespace: default
spec:
    secretName: com-untouchedwagons-testing
    issuerRef:
        name: com-untouchedwagons-testing
        kind: ClusterIssuer
    commonName: '*.testing.untouchedwagons.com'
    dnsNames:
        - testing.untouchedwagons.com
        - '*.testing.untouchedwagons.com'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTlJwY3hwMHBDOWxJaDhx
            YmlHaEM2dEovQXhGZkRkKy94VUFyelFPaWdnCnl4cS93ZXR5czZMVjYyK3JpRHU0
            Sjg2ck5aOFN1dVVJNTMrZGozVFRySDAKLS0tIGxSZkgyNGdhZWZaYWVkZHkySXNx
            dFZScE1mUkFPVHFmbE5Sb2JDTVM0NlUKSKRN0EnHA4dnghkcCqi7ijxhownfE2PS
            yVjVfQk7MpGeXRlo9Pc8atyhWuKIP9AcxqVhQ5YcMmIoCOhxCC6OxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T19:42:51Z"
    mac: ENC[AES256_GCM,data:9c486pEsWF+1Dr0eYVoLPEyON4ZpugejzPPR8+DqADzp3Op/bayCSLykUY9whfH+mrrGxNkv13cY5nVXLuI4TFgFssCu20nQnIxfJgdTpFiwbA3p+4TIUakf7iSRHiEB6MTTjw0ODBH1dwjHIYBHX0YE4Ez2a7ZMJIZtZtR72F4=,iv:Rq2FUokT5PowH5B8H+HzUNuX0V4GewM0K9Xd+ZOQRnI=,tag:BAJni7gMsJ8g0cenkHbNBg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|email)$
    version: 3.8.1
