---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: it-tools
  namespace: default
  labels:
    app: it-tools
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools:2023.11.2-7d94e11
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: default
spec:
  selector:
    app: it-tools
  ports:
    - name: http
      targetPort: 80
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: it-tools.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: it-tools
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal
