apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-linux
  namespace: monitoring
spec:
  scrapeTimeout: 30s
  relabelings:
    - action: replace
      sourceLabels: [__address__]
      regex: ([^:]+)(?::\d+)?   # The first group matches the host, the second matches the port.
      replacement: '$1'
      targetLabel: instance
  staticConfigs:
    - targets:
      - vault.internal.untouchedwagons.com:9100
      - pve-cluster-node-01.internal.untouchedwagons.com:9100
      - pve-cluster-node-02.internal.untouchedwagons.com:9100
      - pve-cluster-node-03.internal.untouchedwagons.com:9100
      - technitium.internal.untouchedwagons.com:9100
      - pve.internal.untouchedwagons.com:9100
      - storage.internal.untouchedwagons.com:9100
