
cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "k3s-prod-node-01"
        devices:
          - name: "/dev/nvme0n1"
      - name: "k3s-prod-node-02"
        devices:
          - name: "/dev/nvme0n1"
      - name: "k3s-prod-node-03"
        devices:
          - name: "/dev/nvme0n1"

ingress:
  # -- Enable an ingress for the ceph-dashboard
  dashboard:
    annotations:
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    host:
      name: ceph.services.untouchedwagons.com
      path: /
    tls:
      - hosts:
        - untouchedwagons.com
        secretName: com-untouchedwagons-services
