---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ispyagentdvr-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 256Mi
