---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ispyagentdvr-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 256Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ispyagentdvr-vol-restore
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: restore
        image: untouchedwagons/simple-restore:1.0.2
        volumeMounts:
          - mountPath: /data
            name: ispyagentdvr-config
          - mountPath: /backups
            name: backups
        env:
          - name: BACKUP_APPEND_DIRECTORY
            value: "/kubernetes/production/ispyagentdvr"
          - name: BACKUP_BASE_NAME
            value: "ispyagentdvr"
      volumes:
        - name: ispyagentdvr-config
          persistentVolumeClaim:
            claimName: ispyagentdvr-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
      restartPolicy: Never