---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ispyagentdvr-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ispyagentdvr-config
