---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    initContainers:
      restore:
        image:
          repository: untouchedwagons/simple-restore
          tag: 1.0.4
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/file-browser"
          BACKUP_BASE_NAME: "file-browser"

    containers:
      main:
        image:
          repository: filebrowser/filebrowser
          tag: v2.28.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']

      backup:
        image:
          repository: untouchedwagons/simple-backup
          tag: 1.1.0
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/file-browser"
          BACKUP_BASE_NAME: "file-browser"
          BACKUP_RETENTION: "24"
          BACKUP_FREQUENCY: "0 0 * * *"

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Services
      gethomepage.dev/icon: filebrowser.png
      gethomepage.dev/name: File Browser
    hosts:
      - host: file-browser.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: file-browser-config
    advancedMounts:
      main: 
        main:
          - path: /database
        backup:
          - path: /data
        restore:
          - path: /data

  settings:
    type: configMap
    name: file-browser
    advancedMounts:
      main: 
        main:
          - path: /config/settings.json
            subPath: settings.json

  nfs-backups:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Backups"
    advancedMounts:
      main: 
        backup:
          - path: /backups
        restore:
          - path: /backups

  nfs-videos:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Videos"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Videos

networkpolicies:
  main:
    controller: main
    policyTypes:
      - Egress
    rules:
      egress:
        - {}

configMaps:
  file-browser:
    enabled: true
    data:
      settings.json: |
        {
          "port": 80,
          "baseURL": "",
          "address": "",
          "log": "stdout",
          "database": "/database/filebrowser.db",
          "root": "/mnt/data/"
        }
