---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 5Gi
