# https://github.com/onedr0p/exportarr/
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-prowlarr
  namespace: monitoring
  labels:
    app: exporter-prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: exporter-prowlarr
  template:
    metadata:
      labels:
        app: exporter-prowlarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: exporter-prowlarr
          image: ghcr.io/onedr0p/exportarr:v1.6.2
          args:
            - prowlarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://prowlarr.servarr.svc.cluster.local:9696"
            - name: APIKEY
              value: "fa88672ddbeb4b5683a009951076bf38"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-prowlarr
  namespace: monitoring
  labels:
    app: exporter-prowlarr
spec:
  selector:
    app: exporter-prowlarr
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-prowlarr
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-prowlarr.monitoring.svc.cluster.local:9707
  metricsPath: /metrics
