# https://github.com/esanchezm/prometheus-exporter-qbittorrent
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-qbittorrent
  namespace: monitoring
  labels:
    app: exporter-qbittorrent
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: exporter-qbittorrent
  template:
    metadata:
      labels:
        app: exporter-qbittorrent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: exporter-qbittorrent
          image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter:v1.4.0
          env:
            - name: QBITTORRENT_HOST
              value: "qbittorrent.default.svc.cluster.local"
            - name: QBITTORRENT_PORT
              value: "8080"
            - name: QBITTORRENT_USER
              value: "admin"
            - name: QBITTORRENT_PASS
              value: "adminadmin"
            - name: EXPORTER_PORT
              value: "9707"
            - name: VERIFY_WEBUI_CERTIFICATE
              value: "False"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-qbittorrent
  namespace: monitoring
  labels:
    app: exporter-qbittorrent
spec:
  selector:
    app: exporter-qbittorrent
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-qbittorrent
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-qbittorrent.monitoring.svc.cluster.local:9707
  metricsPath: /metrics
