---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-nut
  namespace: monitoring
  labels:
    app: exporter-nut
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exporter-nut
  template:
    metadata:
      labels:
        app: exporter-nut
    spec:
      containers:
        - name: nut-exporter
          image: hon95/prometheus-nut-exporter:1.2.1
          env:
            - name: TZ
              value: "America/Toronto"
            - name: HTTP_PATH
              value: "/metrics"
          resources:
            limits:
              cpu: "50m"
              memory: "16Mi"
            requests:
              cpu: "1m"
              memory: "8Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-nut
  namespace: monitoring
spec:
  selector:
    app: exporter-nut
  ports:
    - name: http
      targetPort: 9995
      port: 9995
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-nut
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-nut.monitoring.svc.cluster.local:9995
  params:
    target:
      - ups.internal.untouchedwagons.com
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nut
  namespace: monitoring
spec:
  groups:
    - name: nut
      rules:
        - alert: upsOnBattery
          annotations:
            description: 'UPS "{{ $labels.ups }}" has switched to battery.'
            summary: UPS has switched to battery.
          expr: |-
            nut_ups_status{status="OB"} > 0
          for: 1m
          labels:
            severity: warning
        - alert: upsLowBattery
          annotations:
            description: 'UPS "{{ $labels.ups }}" battery is low.'
            summary: UPS battery is low.
          expr: |-
            nut_ups_status{status="LB"} > 0
          for: 1m
          labels:
            severity: critical
