---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: servarr
  labels:
    app: bazarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        fsGroup: 568
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:15.5
          env:
            - name: INIT_POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: INIT_POSTGRES_USER
              value: "bazarr"
            - name: INIT_POSTGRES_PASS
              value: "GrouseStampAbnormalSpurious"
            - name: INIT_POSTGRES_DBNAME
              value: "bazarr-main"
            - name: INIT_POSTGRES_SUPER_PASS
              value: "TrembleBulwarkBeautifulGossip"
      containers:
        - name: bazarr
          image: ghcr.io/onedr0p/bazarr:1.4.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          env:
            - name: BAZARR__API_KEY
              value: "ad7e2cf067762e0107f77b83b98f838f"
            - name: BAZARR__AUTHENTICATION_METHOD
              value: "None"
            - name: BAZARR__AUTHENTICATION_REQUIRED
              value: "DisabledForLocalAddresses"
            - name: BAZARR__POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: BAZARR__POSTGRES_MAIN_DB
              value: "bazarr-main"
            - name: BAZARR__POSTGRES_USER
              value: "bazarr"
            - name: BAZARR__POSTGRES_PASSWORD
              value: "GrouseStampAbnormalSpurious"
          resources:
            limits:
              memory: 512Mi
              cpu: "4"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: /mnt/data/Videos
              name: videos
        - name: backup
          image: untouchedwagons/simple-backup:1.0.5
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /data
              name: bazarr-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/bazarr"
            - name: BACKUP_BASE_NAME
              value: "bazarr"
            - name: BACKUP_RETENTION
              value: "24"
            - name: BACKUP_FREQUENCY
              value: "0 0 * * *"
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
        - name: videos
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Videos
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: servarr
spec:
  selector:
    app: bazarr
  ports:
    - name: http
      targetPort: 6767
      port: 6767
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: servarr
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: bazarr.services.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: bazarr
            port:
              number: 6767
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-services
