---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app: sabnzbd
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        fsGroup: 568
      initContainers:
        - name: sabnzbd-restore
          image: untouchedwagons/simple-restore:1.0.4
          volumeMounts:
            - mountPath: /data
              name: sabnzbd-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/sabnzbd"
            - name: BACKUP_BASE_NAME
              value: "sabnzbd"
      containers:
        - name: sabnzbd
          image: ghcr.io/onedr0p/sabnzbd:4.1.0 
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /config
              name: sabnzbd-config
            - mountPath: /mnt/data/Usenet
              name: usenet
            - mountPath: /tmp
              name: tmp
        - name: backup
          image: untouchedwagons/simple-backup:1.0.5
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /data
              name: sabnzbd-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/sabnzbd"
            - name: BACKUP_BASE_NAME
              value: "sabnzbd"
            - name: BACKUP_RETENTION
              value: "24"
            - name: BACKUP_FREQUENCY
              value: "0 0 * * *"
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Backups
        - name: usenet
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Usenet
        - name: tmp
          emptyDir:
            medium: Memory
          
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
spec:
  selector:
    app: sabnzbd
  ports:
    - name: http
      targetPort: 8080
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: sabnzbd.services.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: sabnzbd
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal-services
