---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sabnzbd
          tag: 4.2.3

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Download Clients
      gethomepage.dev/icon: sabnzbd.png
      gethomepage.dev/name: SabNZBd
      gethomepage.dev/widget.type: "sabnzbd"
      gethomepage.dev/widget.url: "https://sabnzbd.services.untouchedwagons.com"
      gethomepage.dev/widget.key: "441c51b1799e551d7b4757b179fe7e96"
    hosts:
      - host: sabnzbd.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: sabnzbd-config
    advancedMounts:
      main: 
        main:
          - path: /config

  tmp:
    type: emptyDir
    advancedMounts:
      main: 
        main:
          - path: /tmp

  nfs-usenet:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Usenet"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Usenet
