---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    initContainers:
      restore:
        image:
          repository: untouchedwagons/simple-restore
          tag: 1.0.4
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/sabnzbd"
          BACKUP_BASE_NAME: "sabnzbd"

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sabnzbd
          tag: 4.1.0

      backup:
        image:
          repository: untouchedwagons/simple-backup
          tag: 1.0.5
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/sabnzbd"
          BACKUP_BASE_NAME: "sabnzbd"
          BACKUP_RETENTION: "24"
          BACKUP_FREQUENCY: "0 0 * * *"

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    hosts:
      - host: sabnzbd.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      main: 
        main:
          - path: /config
        backup:
          - path: /data
        restore:
          - path: /data

  tmp:
    type: emptyDir
    advancedMounts:
      main: 
        main:
          - path: /tmp

  nfs-backups:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Backups"
    advancedMounts:
      main: 
        backup:
          - path: /backups
        restore:
          - path: /backups

  nfs-usenet:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Usenet"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Usenet
