---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: default
  labels:
    app: radarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 30000
      containers:
        - name: radarr
          image: ghcr.io/onedr0p/radarr:5.1.3.8246
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 1Gi
              cpu: "4"
            requests:
              memory: 512Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /mnt/data/Videos
              name: videos
            - mountPath: /mnt/data/Torrents
              name: torrents
            - mountPath: /mnt/data/Usenet
              name: usenet
        - name: backup
          image: untouchedwagons/simple-backup:1.0.4
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /data
              name: radarr-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/radarr"
            - name: BACKUP_BASE_NAME
              value: "radarr"
            - name: BACKUP_RETENTION
              value: "24"
            - name: BACKUP_FREQUENCY
              value: "0 */4 * * *"
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
        - name: videos
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Videos
        - name: torrents
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Torrents
        - name: usenet
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Usenet
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
spec:
  selector:
    app: radarr
  ports:
    - name: http
      targetPort: 7878
      port: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: radarr.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: radarr
            port:
              number: 7878
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal