---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ddclient
  namespace: default
  labels:
    app: ddclient
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      containers:
        - name: ddclient
          image: matthewhuie/ddclient:2ea45fd
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.1"
          volumeMounts:
            - mountPath: /etc/ddclient/ddclient.conf
              name: ddclient-config
              subPath: ddclient.conf

      volumes:
        - name: ddclient-config
          configMap:
              name: ddclient
