---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deepstack
  namespace: default
  labels:
    app: deepstack
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deepstack
  template:
    metadata:
      labels:
        app: deepstack
    spec:
      containers:
        - name: deepstack
          image: deepquestai/deepstack:cpu-2022.01.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: 256Mi
              cpu: "0.2"
            limits:
              memory: 512Mi
              cpu: "2"
          env:
            - name: VISION-DETECTION
              value: "True"

---
apiVersion: v1
kind: Service
metadata:
  name: deepstack
  namespace: default
spec:
  selector:
    app: deepstack
  ports:
    - name: http
      targetPort: 5000
      port: 5000
