apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secrets
    namespace: default
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:j4i5KQYN,iv:5wPh2IFCXTHtFN+adIu++x3GdncTwvZIypSl8BxFaec=,tag:vVOLeDD6gkl3qsDgJv5NDA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:c8LeNS74xuFe,iv:Wdt9aUwMsIFT9ZIv4cXH/w2gBPCIgidxidaIkytbuDg=,tag:WSNpbz3goWk9xyeP3gkqDw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:OjT5bExr3I6MPk3FbKSEFPwTwbFxo7v1b1EhuI4seXUFEMpWqi3yFgpU54g=,iv:yhn4l8YsfzbEbaEUWxWpOqGWZ3LlS2hsjkbb2uJdCZM=,tag:sdxTdnhNv06c7WQ1VV01DQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:N3LYAEKJ9cc4WcsUp594TSEpoB08qam63Z2De/Jm4rJtaykHhNf50kGBEMs=,iv:ivlgLBsTqzb8tpMDZlK//2YXVVrUxvH070Wt7BlWii4=,tag:/FUGncpMnF+jmRN8eQ6sNQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:k8ADVU77Ckww0RAyC8rPrg==,iv:8TQ0Wx7rR6TT9XxyWJhK9Tg4wr+DIEI54PU5WBrPcgQ=,tag:XmCfnye6gOefd17DckXIyQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:gHTPN9P0,iv:jCSVjTtiTD8YCu4Sh4oADAXnTDIDoK5JvleBA7H5F9A=,tag:28IRWA8Eho6YzUkOXMm15g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ3FQR3pqZ0plM25jdFJ4
            amh5dWFxQ2JwdHJDK2g5cGxHSUtXa1JKQWgwCldpZTZ3Q0wycW9pRCtDOTJiWE0y
            a25xSEZWTWRSWTRMVTkxS1BRd2xRSjAKLS0tIEtubWptRit1eHc4THQramtOL3o2
            cDBuVFVrM0JGUkQ0RncyOHo0MHhhOUEK4mhMPKNN9ArZ7h2PiMNk2dnqW+AdCZro
            4cexr4p2xTbb3Gvdo3pImt9WY9enf/GNicUye1yJI8ZBlRqWULvosQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T20:57:43Z"
    mac: ENC[AES256_GCM,data:Xv5Kohk8EKfeJ3vfYnWTQyPk6myNWZxIk1xoty1gC3L2ohDsrg/HQfBfwPmJC+UHQN7BKTVwVNIW47reJTVk1mhN3RgPpkZsd7GFL1YaH8gUf9vA1egt/pC4GszHs3sOgfSWPl8dSibtnwkVFpq0ccWV+OM59krOO4a08W+nPWM=,iv:/Y6q4hfNzYnfU0sI96J7tSDuq6ZZr4832lP+yrfg6lQ=,tag:Q1jp/FJldRrGMoQgLoedhA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.8.0
