# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json
defaultPodOptions:
    securityContext:
        fsGroup: 568
controllers:
    main:
        strategy: Recreate
        initContainers:
            restore:
                image:
                    repository: untouchedwagons/simple-restore
                    tag: 1.0.4
                env:
                    BACKUP_APPEND_DIRECTORY: /kubernetes/production/qbittorrent
                    BACKUP_BASE_NAME: qbittorrent
        containers:
            gluten:
                image:
                    repository: qmcgaw/gluetun
                    tag: v3.38.0
                securityContext:
                    privileged: true
                    capabilities:
                        add:
                            - NET_ADMIN
                env:
                    VPN_SERVICE_PROVIDER: airvpn
                    VPN_TYPE: wireguard
                    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gGwbu+1e82/Mc/3pY9oY695ZJNMm/AFyIq6ohrTfx9S1XiL9VMjgqH3KX4o=,iv:cZls55y0qKopTzgqArCLSxNUixybPtti2CqjTZdxqNQ=,tag:j4uLmjCsyVz3uwDTqG4few==,type:str]
                    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:jl5AvA95hpiDyb8TCxpgBkbF/J2+6G/II/gAAWMMDNKSBN9E9YdNFY7YZOQ=,iv:/0sWfJzQhpU44JTcOAM17Vs2Eie6q5tXexOpxRLuYEQ=,tag:bErMHJY89DqBQLH1oz7SIQ==,type:str]
                    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Ex7e6zJ3xWG/0QNrd57eoA==,iv:KBGpUZQRph+sRwgpOzVHeNmuG+UoMHvfcpmYKKw2jvI=,tag:AIoVeMTzg9rKrzdauOIitQ==,type:str]
                    SERVER_COUNTRIES: Canada
                    WIREGUARD_MTU: ENC[AES256_GCM,data:0wr4yw==,iv:it3BoVmK2gN9UwiL8VtLtURs6qf+bQyZAAOYlj2KxU0=,tag:ltQHOGe3eBz2OV5trKGowg==,type:str]
                    FIREWALL_VPN_INPUT_PORTS: "41183"
                    FIREWALL_INPUT_PORTS: 8080,8888
                    FIREWALL_OUTBOUND_SUBNETS: 192.168.0.0/16
                    HTTPPROXY: "on"
                    HTTPPROXY_STEALTH: "on"
                probes:
                    liveness:
                        enabled: true
                        custom: true
                        spec:
                            exec:
                                command:
                                    - /gluetun-entrypoint
                                    - healthcheck
                            initialDelaySeconds: 15
                            periodSeconds: 15
            main:
                image:
                    repository: ghcr.io/onedr0p/qbittorrent
                    tag: 4.6.4
                env:
                    QBITTORRENT__PORT: "8080"
                    QBITTORRENT__BT_PORT: "41183"
            backup:
                image:
                    repository: untouchedwagons/simple-backup
                    tag: 1.1.0
                env:
                    BACKUP_APPEND_DIRECTORY: /kubernetes/production/qbittorrent
                    BACKUP_BASE_NAME: qbittorrent
                    BACKUP_RETENTION: "24"
                    BACKUP_FREQUENCY: 0 0 * * *
service:
    main:
        controller: main
        ports:
            http:
                port: 8080
    gluetun:
        controller: main
        type: LoadBalancer
        ports:
            proxy:
                port: 8888
ingress:
    main:
        annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Download Clients
            gethomepage.dev/icon: qbittorrent.png
            gethomepage.dev/name: QBitTorrent
            gethomepage.dev/widget.type: qbittorrent
            gethomepage.dev/widget.url: https://qbittorrent.services.untouchedwagons.com
            gethomepage.dev/widget.user: admin
            gethomepage.dev/widget.password: adminadmin
        hosts:
            - host: qbittorrent.services.untouchedwagons.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http
        tls:
            - hosts:
                - untouchedwagons.com
              secretName: com-untouchedwagons-services
persistence:
    config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        dataSourceRef:
            kind: ReplicationDestination
            apiGroup: volsync.backube
            name: qbittorrent-config
        advancedMounts:
            main:
                main:
                    - path: /config
                backup:
                    - path: /data
                restore:
                    - path: /data
    nfs-backups:
        type: nfs
        server: 192.168.35.30
        path: /mnt/tank/Media/Backups
        advancedMounts:
            main:
                backup:
                    - path: /backups
                restore:
                    - path: /backups
    nfs-torrents:
        type: nfs
        server: 192.168.35.30
        path: /mnt/tank/Media/Torrents
        advancedMounts:
            main:
                main:
                    - path: /mnt/data/Torrents
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcWpZYXBMYzhlQWxXRUk0
            d1RyUDJVMjFsV3U3aUNVc0tFbG0yRFh3S3dnCmFwK2xZTy9uUXJQK0xiK2dEejNa
            ejE0UlFnRllSeHlmL1UvL1I4em1DNW8KLS0tIGlLandnQ2JMOTNVTjZ1SmFHd1I0
            dWtTc1Z6VkNMLzJSVDJ6WHphejhnNzQKDtvNyDAkFY9ZKVdHOO2vfEdhi92KOtq3
            JLzc2LW0tJqpZyL3aQgNSHZBa1bIKB3TTmyfGbg0TP+BhPfui29pbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T15:56:53Z"
    mac: ENC[AES256_GCM,data:x6m04PGp3xk9DWKFma0kFVbV3Crq12AqCAEB41ZDe0X49iJfY2SkYchTFRs6Y4ANJOe6sNEGFMhaTPV4cjaZPzYcSRN7n4fE+GVLozoH25lFuburls1v80GTh3igABPAZ3zExzwmZqoV3vo01tSffWFxrkPbuGDq+HCOAlrstDo=,iv:6tzoycc3d4xLVFA9HskDMKiHnnWGTc+DFvtg8qKimI4=,tag:wyMsl4dahr/wPSuDRk05pA==,type:str]
    pgp: []
    encrypted_regex: ^(WIREGUARD_)
    version: 3.8.1
