# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/values.schema.json
defaultPodOptions:
    securityContext:
        fsGroup: 568
    annotations:
        enable.version-checker.io/gluetun: "true"
        match-regex.version-checker.io/gluetun: ^v\d+\.\d+\.\d+$
        enable.version-checker.io/main: "true"
controllers:
    main:
        strategy: Recreate
        containers:
            gluetun:
                image:
                    repository: qmcgaw/gluetun
                    tag: v3.38.0
                    pullPolicy: Always
                securityContext:
                    privileged: true
                    capabilities:
                        add:
                            - NET_ADMIN
                env:
                    VPN_SERVICE_PROVIDER: airvpn
                    VPN_TYPE: wireguard
                    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:z/g7hL5RZGso0T1pfCEhyG2UVzFkoTqe1puKTZrUhQJMM6beblrZ5StwiJM=,iv:mlUhV+gFkxfxGrMiiYnrnE+fYUE4ZBB0VwCV/AOWYsc=,tag:Cv8mgLQHD/fMxqy9OHbAhg==,type:str]
                    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Wqb+wJBdElb8yfKLMXqBYYzV1YTPYxzz69dgRKlkhlxWoESQmh5atfv+g00=,iv:/BrKRaewNJaXAoxq74CEdGSjZWIxlLrvcjDhLBtnHMU=,tag:BGFUETmp5mN69DlCWVIg7Q==,type:str]
                    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:wQh1pCmlP9BlrwgM5OIIxQ==,iv:1qNXIArRJJnX+3ILraptruvhSMj/pLu04DM5d+PAV0Q=,tag:B5NmmpBjdJcEfZL3rgbRdg==,type:str]
                    SERVER_COUNTRIES: Canada
                    WIREGUARD_MTU: ENC[AES256_GCM,data:bvUojA==,iv:V7B88ciEj8M4mcTuF/TK/j9XoDtCzK3ajiN7n+3LaQ4=,tag:xw142pP2Lfz8A2Ia6LCOUQ==,type:str]
                    FIREWALL_VPN_INPUT_PORTS: "41183"
                    FIREWALL_INPUT_PORTS: 8080,8888
                    FIREWALL_OUTBOUND_SUBNETS: 192.168.0.0/16
                    HTTPPROXY: "on"
                    HTTPPROXY_STEALTH: "on"
                probes:
                    liveness:
                        enabled: true
                        custom: true
                        spec:
                            exec:
                                command:
                                    - /gluetun-entrypoint
                                    - healthcheck
                            initialDelaySeconds: 15
                            periodSeconds: 15
            main:
                image:
                    repository: ghcr.io/onedr0p/qbittorrent
                    tag: 4.6.4
                    pullPolicy: Always
                env:
                    QBITTORRENT__PORT: "8080"
                    QBITTORRENT__BT_PORT: "41183"
                resources:
                    requests:
                        memory: 512Mi
                        cpu: 150m
                    limits:
                        memory: 4096Mi
                        cpu: "1"
service:
    main:
        controller: main
        ports:
            http:
                port: 8080
    gluetun:
        controller: main
        type: LoadBalancer
        ports:
            proxy:
                port: 8888
ingress:
    main:
        annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Download Clients
            gethomepage.dev/icon: qbittorrent.png
            gethomepage.dev/name: QBitTorrent
            gethomepage.dev/widget.type: qbittorrent
            gethomepage.dev/widget.url: https://qbittorrent.services.untouchedwagons.com
            gethomepage.dev/widget.user: admin
            gethomepage.dev/widget.password: adminadmin
        hosts:
            - host: qbittorrent.services.untouchedwagons.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http
        tls:
            - hosts:
                - untouchedwagons.com
              secretName: com-untouchedwagons-services
persistence:
    config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        dataSourceRef:
            kind: ReplicationDestination
            apiGroup: volsync.backube
            name: qbittorrent-config
        advancedMounts:
            main:
                main:
                    - path: /config
    nfs-torrents:
        type: nfs
        server: 192.168.35.30
        path: /mnt/tank/Media/Torrents
        advancedMounts:
            main:
                main:
                    - path: /mnt/data/Torrents
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcWpZYXBMYzhlQWxXRUk0
            d1RyUDJVMjFsV3U3aUNVc0tFbG0yRFh3S3dnCmFwK2xZTy9uUXJQK0xiK2dEejNa
            ejE0UlFnRllSeHlmL1UvL1I4em1DNW8KLS0tIGlLandnQ2JMOTNVTjZ1SmFHd1I0
            dWtTc1Z6VkNMLzJSVDJ6WHphejhnNzQKDtvNyDAkFY9ZKVdHOO2vfEdhi92KOtq3
            JLzc2LW0tJqpZyL3aQgNSHZBa1bIKB3TTmyfGbg0TP+BhPfui29pbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T20:31:06Z"
    mac: ENC[AES256_GCM,data:Kij+9/Eu2hXuZroa5UOgIXVLG/zrj1BCRxLGKvhEdwp5wG4Z+DtYBUqvpTYgrjF25bop9/ow82p8Vb7HQu0TfLaxJ0TTUcCcjiuubSh7hgUHg9SsG6C7TXhPZwarx0i+zVx9/nXFYMl5IdHIzJyxsSUJ5hYTZupSaGZiEjRH06w=,iv:DaQz9RrdAI/2wfuacaDy0S7Ko8vMALXvVXSxuypAsu8=,tag:p209U89iYlYkZK3aiY3vvg==,type:str]
    pgp: []
    encrypted_regex: ^(WIREGUARD_)
    version: 3.9.0
