apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-flaresolverr
  namespace: monitoring
spec:
  scrapeTimeout: 30s
  relabelings:
    - action: replace
      sourceLabels: [__address__]
      regex: ([^:]+)(?::\d+)?   # The first group matches the host, the second matches the port.
      replacement: '$1'
      targetLabel: instance
  staticConfigs:
    - targets:
      - flaresolverr.servarr.svc.cluster.local:8192
