apiVersion: v1
kind: ConfigMap
metadata:
    name: rclone
    namespace: networking
data:
    rclone.conf: ENC[AES256_GCM,data:DjR/NZEEpO8GfrnDSh47eTffKsb3OQEs2AC6MxE6sOpxF/B9xE1Hqk5wWNLcIp6eu3ehQ/AGpKpxN8HNS1jxkMqV4T2BM5LKgIbmwndsusSij04g5mPh+kSR7eQXG97qg2UXRmXPgk2c69ZHljjMT3C0P2HLgr/9C95msD3DQKhi9o78b1wpxg55YZ4wYa9IgyL+YegkBkOCU0atbg575CbYGryrMss7CqxUAG+qkTiIeTEcWm6KuwxaBEu6GMI2aMH9pKP/w17TJC1ESVJS0q5Cl2BXruJZE/uwHZCD8IlTgg8pTccjTVg7Eki9FJaCu69GJRs+7LvYdcILPmVpH3Xh9HELHns5Kl/plE43++KPiOCLweMU521UzzHRQ1DAQKG02hv8nBs+MgXmIRHLEbyK3ifCqFOn0MyE7SyIUcjeoN5vX6m+rnwFfEyLL2pCFVhP256Ld6+HC4fzNdSRn2T5SqlLauEvhQU=,iv:InRfxprStsCed6QNhDSzCj2yVZnOOKyduDkeVglcQlA=,tag:hnd9jgY/H9E+X7GfnjOKEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucXJSZWpxMHJSRWxyOU5q
            dzVadDQ5WFpNZ1dvRWoyZlN4bXhWVC9tdHpVCjFtenJOYzd2Vy9HQllJeUxJWlZO
            Tm9TR2MyamtqWmRGVTJYTGpUTE5CMEUKLS0tIDZwRXFaeFhISmJFc0o5SzlIdmQz
            WWIrRlN1VVk4VUFWa3ZKN0tURmFqcm8KeuVGT+QGtKVXv22mRMeQTENUokAG6oe6
            rcgI0JnoobHS/qElIobJBVcPuqUSeBn33ald9M7OLx8bSWIMWgJcPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T01:27:54Z"
    mac: ENC[AES256_GCM,data:PlLHrXggUqmMeutNQwxWN+Iz4aK4xK3kRKmYG4C6k7jB7qmHhWVA4PrBECGNGMlLt84p430QGXdP4m3vEzUVsn0Z1L0RQHOcN+JSpAmrApRu077/MZiJsEkXnx2rMMIzYSvPIgeHP9hOJ4L3yRYbYbvYrUf49bVt7IBoW2EDv+E=,iv:hkHd3ywObWrpN2VUOg40hmePvwjY3gthpZGRv5vRt/s=,tag:SlqQTI45rsjpRxveXd3wfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|volumeMounts|volumes)$
    version: 3.9.0
---
apiVersion: batch/v1
kind: CronJob
metadata:
    name: rclone
    namespace: networking
spec:
    schedule: 0 0 * * *
    jobTemplate:
        spec:
            ttlSecondsAfterFinished: 10
            template:
                spec:
                    restartPolicy: OnFailure
                    containers:
                        - name: rclone
                          image: rclone/rclone:1.67
                          command:
                            - /bin/sh
                            - -ec
                            - |
                              rclone sync --config=/root/rclone.conf /mnt/data/ Wasabi-enc:jb-media --exclude "/Videos/Movies/" --exclude "/Videos/TV Shows/" --exclude "/Videos/Anime/" --exclude "/Videos/Anime Movies/"
                          volumeMounts:
                            - mountPath: ENC[AES256_GCM,data:z1gBHAJq24koVzwYMR0QYG8=,iv:urz6Ks9+by+8rBGg5/onXHf6n/V+4BKYesPwUU2RO8U=,tag:kAy1OMwT4g+7tB5pcxcpGQ==,type:str]
                              name: ENC[AES256_GCM,data:zwbTtDIN,iv:Bd0ka0uMDSinRjlbVyqbs2dtKo31+mkd2bODKSmsRI4=,tag:oL9KAbIls8OTkKdfLGnGkw==,type:str]
                              subPath: ENC[AES256_GCM,data:bjlBCngC5Y2UlY0=,iv:4/YCvHnGtRkFuwfqXppatOZ25E3exdwL/9yGIHvW3kM=,tag:bBDOSiVP81S44EnQecKKNg==,type:str]
                            - mountPath: ENC[AES256_GCM,data:YVpbQ8KEqcs1Ec04coV1EyU=,iv:CN5CrqiKdzgRB0iGcm3niQsB0r5LR5dpVluGRuXY/pw=,tag:PFRmdRq9VHS4vEAQx+XAbA==,type:str]
                              name: ENC[AES256_GCM,data:13Mpn+Kh3Q==,iv:jgt8GRmN8m1j8uqDs2eKl62qZAkdU/V8H4jhecBvypk=,tag:ZDtbgKNAnD2+P5BxglzEuw==,type:str]
                            - mountPath: ENC[AES256_GCM,data:kyb+JJ1+SMujlaO9oGBM,iv:WuSo1ZlaaW7PQ/0baOFNnpuNP99tF4VsiaaomRnJtjQ=,tag:TIz2ia8ERMuXOtiPJiGkow==,type:str]
                              name: ENC[AES256_GCM,data:kkGC2gE=,iv:8vYxzoDGelrJZw5IkySPuLrunoJFKxm84Ws7bydwgKs=,tag:PC4kudP6KMf+NNMJ/L5pig==,type:str]
                            - mountPath: ENC[AES256_GCM,data:ltgQe8q6Y/iAh6jwEBU=,iv:u+9PYlFvkDV/NaL8Ma617/uXoGccnpUOiLN5Ios/x9U=,tag:NNkz0Qg02Mib8jLEi8tvxA==,type:str]
                              name: ENC[AES256_GCM,data:3Fs44A==,iv:kzyVhnXZP3EtfPKUd7Pr9imykYN56uI2549w7uaPrBE=,tag:aVomfbLUw66PSDfjOsWlZQ==,type:str]
                            - mountPath: ENC[AES256_GCM,data:0I/x7iKD2BlGoe0GCULNOLtws0X4OM4=,iv:BiYvqp+kYAIQXi20vgQySNXcsTcfw5ES+U6iczvrSng=,tag:EvMz9afp8IcfQxzOoUew1w==,type:str]
                              name: ENC[AES256_GCM,data:Weo6hSVxkmvHEtnhOQ==,iv:ZwaqvLF0+Du+ImeVJTH3kjlNG9Yap53irUaisjpsKCc=,tag:BY9eBck7IxdaAgkiU88zgg==,type:str]
                            - mountPath: ENC[AES256_GCM,data:OBcEU6LxYo5OB+zQfJJ1,iv:g5NvksMKWkQ9wSmHAL9dANXPp1ZtXKfJx0N2Z36GSLY=,tag:EwLXb0oZ/bhh8Y9WhXZrbA==,type:str]
                              name: ENC[AES256_GCM,data:fS7hJVc=,iv:ya3Lfz1M0e1+MwR1lSI3oHv0whOklOOPfO+H/Qk+AH4=,tag:B6FiZJGd7D/ttNrNo6xsWw==,type:str]
                            - mountPath: ENC[AES256_GCM,data:jq/SPWW1AhctaGR18xoULvSf,iv:pdOIbr6K5h/zJwQN62w3GhMRkHNPX67BmAwTSfQtHLQ=,tag:rlKb809MnAihCnbpRGvk4A==,type:str]
                              name: ENC[AES256_GCM,data:jzHMzI3EPdM=,iv:eeKrEfgkoOrz3QZvhSZZcKX/md180joaepbhd+6AQ8o=,tag:S1C9m98jNzF/1Q4eljnr0w==,type:str]
                            - mountPath: ENC[AES256_GCM,data:zn9S3bRwJXfeBgtPoso=,iv:HR1s/pNhxVMc0w9yV7ORvWLHWIed8gcCF9TT7YUcqLw=,tag:zhdTHkR8iCb0YE1pVnCrLw==,type:str]
                              name: ENC[AES256_GCM,data:FBthMA==,iv:8sLx0PItEX+6iR4Xz3L9NAC3vrvW8VYvcmtCufsaVaw=,tag:w1Dz60BXjZ7oha2sKGA74A==,type:str]
                            - mountPath: ENC[AES256_GCM,data:UH8K35Yy3yNL/TGPbZ9v8FfH,iv:coMCpoZBXBBTYbTH4m/Ungtv5bKmkb1WYl34g9O4bKQ=,tag:ooQapU8/ML6mqDfrbAG+Ig==,type:str]
                              name: ENC[AES256_GCM,data:umwmm70728o=,iv:OT5OIqJVxrC/7sRU80iodvCpJj/KB7VIdpyXpuq6B2M=,tag:/mM5kTAheqOi0i8cRnMkpQ==,type:str]
                            - mountPath: ENC[AES256_GCM,data:FpUpbnWoDRgZeRSDjADpdELkwjPX,iv:wzER6zNbOlYDLHjdfd25cHwbxfbu6UFB42a7cTMSe/s=,tag:azNK+cB76BrnSbpfYnwNFA==,type:str]
                              name: ENC[AES256_GCM,data:8mAmZQZ2bZdqPtY=,iv:sWaK0zb8CiA6NIm4oKMTjuf1RZyK7Vg4Rplex4IRAi4=,tag:N134IwxU1LiOZC9sBVKFiw==,type:str]
                            - mountPath: ENC[AES256_GCM,data:MJ0r0OMPzY9KEeGmipvzkg==,iv:d8ZGhq1y40QLwvIGMocL9prDknjN5t+DalS5CqxP9hU=,tag:owQvU6Af9tWzgJ75yq4c0A==,type:str]
                              name: ENC[AES256_GCM,data:dYOVvYvI,iv:WTP4twoEghYOaUm0oMdwANzfT8yeMXIb3dB9RbetAAs=,tag:a2PCNyIz3uRAagH0dO9JUQ==,type:str]
                    volumes:
                        - name: ENC[AES256_GCM,data:Hz1n86xm,iv:U7F94m2xYJGALTgGPOtfWHKB9faCQkR/1Hr1i4yoBqY=,tag:fYEN8jG4czgppEMtcdUirg==,type:str]
                          configMap:
                            name: ENC[AES256_GCM,data:JbAuQPfI,iv:qGEtkOfmKpH5rouBSaJRdyHcRbHWUOqmqo2zOYxlOkU=,tag:7Dwh/vdmAtQdFz3CI/It5g==,type:str]
                        - name: ENC[AES256_GCM,data:Wuog8J+oCA==,iv:+GOZJT0md9P7+UF4+sFkAt2VXvSDYD3EmvTSktV5saM=,tag:VL07nqRd10xbxCUwH4PXJg==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:dv8OFKyVgGpdEp7Y1cSTMsNyTnGvJbc=,iv:5FBWyzC7arzmcul0NT2nhM70RZrk50rQIrNpay8ocxA=,tag:4Q7lyCI4kIhd44SrWF20wQ==,type:str]
                        - name: ENC[AES256_GCM,data:kbfpJuo=,iv:8LftSj9UpR/oOD3ZW8oSt19fmoor+gH+uGsaZHaHe3o=,tag:t7+p176AKJYBXyu1IYXBfA==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:ZttS8yx7Z77mvylemuaSlBUVfrUh,iv:mVzxp71zEzVWi27/bFRlYla5BGmm2DRMkEO7cxDmjgU=,tag:nI7mV6PKWGydGIpA38pzHA==,type:str]
                        - name: ENC[AES256_GCM,data:K7+o0A==,iv:669VYMljCA4lU4aABmYME7K1rkKS9Kw8/adU1trOBpY=,tag:AtpwbRoZSsKqkLF0FvzOJQ==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:szIYmci/rx2bU2MhU8H3IZm1N5A=,iv:yHUowdC3tTPcz1/3tzioLnkO/nF/VK7wXs/ofyeAbmI=,tag:h2wh6xonbYqBmAV8FvX2tw==,type:str]
                        - name: ENC[AES256_GCM,data:TCamCwrfi6yTKUUL1g==,iv:q4hL4cXdUA/MlnATqgVo3KcEsTId4pxwU6W5N6PE8VE=,tag:cq53qKzsV2sjFu9C9aZ7gA==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:QPWDWZDyYN07YJuAO07OGHMzpqMirL8poqbnhYE=,iv:EoTnzlRNXM2In0TndXG6a0rx443tAi1miinj4FQdVSc=,tag:h7gH4rnpi1Kr7Q7L9ew85w==,type:str]
                        - name: ENC[AES256_GCM,data:wOJPW4g=,iv:t4ZLk0Egut2rMx0FB8q/A3LfFN2LJB33Gf+EUOz9Q60=,tag:ySuq7rYfhAb/53Yr+XLp+A==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:tGOTIDR3MYb8omMbTBFjxFJNck3b,iv:4Mz3LlJUD0pPVRZU8ApV7B8ywuWNfZE5y9LtAppEaro=,tag:zLhbWWlRlrqXBFNZ2L13jw==,type:str]
                        - name: ENC[AES256_GCM,data:YagazMd0ZNY=,iv:h8FdL5xsk7+JyDslAnC/s+VpCTYzIdAhK8L+7XTmIiE=,tag:d79ed41OCPJepayibb7E7A==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:z1V4MTsZ2ZZMHG4MMLbSqqGvR3/EtMB2,iv:NwSr7oOwPROMY34lvsVOKNrSA30o4y1nJlxXMdF4M/s=,tag:XtFAWOOagrHO+Gxw6M6bnA==,type:str]
                        - name: ENC[AES256_GCM,data:jgE25A==,iv:bsBo91WMmFdSj0nv8EKePLEVQIlodEVT4plyyiD0Tco=,tag:OZdZC42mCISkdwpe/82sjQ==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:h3cp2V90knS6ysz4V+/JemKtY2A=,iv:m8dqzStNRva4fPvSE8DeOEOlIG2pJs6rApCyDQyxnkc=,tag:qGCPgO9KgbafdDfHM1Jh5w==,type:str]
                        - name: ENC[AES256_GCM,data:+iqdXBZu8zc=,iv:EzRB5KJK3r6Knc6sRmU3sedpr4TqUp5irqpQrMQ4WbI=,tag:oU9bAethElo1TWJ3SytD2Q==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:3GKTvazAJnX7Wx97QMXRiXTeTAWJ6rox,iv:zwQe+BV6+GFWzTFXTnOT95ONBqld7gN4leNsYOihc7g=,tag:hggR925YSEwlJkflVgDF4w==,type:str]
                        - name: ENC[AES256_GCM,data:g7SBmtopjwBOSTI=,iv:qChWUZi8o4xAjwmHwafiPx2rhmgcupAN2V+O1gnQhag=,tag:b5N7X6as+FSwyBbjLcv7gg==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:Y5m1ds3QWA0I/bZ31TbMg2CLRSk7c7EYBk/4,iv:VXjBHKlTWmiLUVYHv27JZ910TvAvKsT6JKBtuBulFO8=,tag:LaWsJSIQbFQyexCN8GVuBA==,type:str]
                        - name: ENC[AES256_GCM,data:sPBXPdeG,iv:4ENn0tW2Z9CpeWSRxFdcLST/CSa5Kp2DFqQhdCHtCqs=,tag:/+pOmmqV58K3iCi1dZV7WQ==,type:str]
                          nfs:
                            server: ENC[AES256_GCM,data:7LKtLmikoBO7vjbQmQ==,iv:TstvCKO7wmZe381IVIurUjW/B2vaT92pXSJAnfxaSx0=,tag:U2+tyu3QS55HfZX7TxTJ/Q==,type:str]
                            path: ENC[AES256_GCM,data:Wm701Tc7qznxN/9u/mS+yE/Xcqs7wg==,iv:POQzJGUM8SuQu7kNc20cAMnwKMSpvMQPh5SVYys2xOA=,tag:vDhIYD/C4JhjzUssD6ZoIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucXJSZWpxMHJSRWxyOU5q
            dzVadDQ5WFpNZ1dvRWoyZlN4bXhWVC9tdHpVCjFtenJOYzd2Vy9HQllJeUxJWlZO
            Tm9TR2MyamtqWmRGVTJYTGpUTE5CMEUKLS0tIDZwRXFaeFhISmJFc0o5SzlIdmQz
            WWIrRlN1VVk4VUFWa3ZKN0tURmFqcm8KeuVGT+QGtKVXv22mRMeQTENUokAG6oe6
            rcgI0JnoobHS/qElIobJBVcPuqUSeBn33ald9M7OLx8bSWIMWgJcPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T01:27:54Z"
    mac: ENC[AES256_GCM,data:PlLHrXggUqmMeutNQwxWN+Iz4aK4xK3kRKmYG4C6k7jB7qmHhWVA4PrBECGNGMlLt84p430QGXdP4m3vEzUVsn0Z1L0RQHOcN+JSpAmrApRu077/MZiJsEkXnx2rMMIzYSvPIgeHP9hOJ4L3yRYbYbvYrUf49bVt7IBoW2EDv+E=,iv:hkHd3ywObWrpN2VUOg40hmePvwjY3gthpZGRv5vRt/s=,tag:SlqQTI45rsjpRxveXd3wfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|volumeMounts|volumes)$
    version: 3.9.0
