---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-nvidia
  namespace: monitoring
  labels:
    app: exporter-nvidia
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exporter-nvidia
  template:
    metadata:
      labels:
        app: exporter-nvidia
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: nvidia-smi-exporter
          image: utkuozdemir/nvidia_gpu_exporter:1.2.0
          resources:
            limits:
              memory: 1Gi
              cpu: 1
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-nvidia
  namespace: monitoring
spec:
  selector:
    app: exporter-nvidia
  ports:
    - name: http
      targetPort: 9835
      port: 9835
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-nvidia
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-nvidia.monitoring.svc.cluster.local:9835
  metricsPath: /metrics
