persistence:
  enabled: true
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: grafana.png
    gethomepage.dev/name: Grafana
  hosts:
    - grafana.services.untouchedwagons.com
  tls:
    - secretName: com-untouchedwagons-services
      hosts:
        - grafana.services.untouchedwagons.com
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true