persistence:
  enabled: true
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.services.internal.untouchedwagons.com
  tls:
    - secretName: com-untouchedwagons-internal-services
      hosts:
        - grafana.services.internal.untouchedwagons.com
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
