---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.3/charts/library/common/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: nginx
          tag: stable-alpine-slim

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    className: nginx
    hosts:
      - host: nginx.testing.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-testing
