
ingress:
  enabled: true
  hosts:
    - host: pgadmin4.internal.untouchedwagons.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: com-untouchedwagons-internal
      hosts:
        - pgadmin4.internal.untouchedwagons.com

env:
  email: UntouchedWagons@untouchedwagons.com
  password: AimSterileBannerPork

