---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    fsGroup: 5050
    runAsGroup: 5050
    runAsUser: 5050

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: dpage/pgadmin4
          tag: 8.5
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - all
        #     add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
          PGADMIN_DEFAULT_EMAIL: "UntouchedWagons@untouchedwagons.com"
          PGADMIN_DEFAULT_PASSWORD: "AimSterileBannerPork"
          PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    annotations:
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Services
      gethomepage.dev/icon: pgadmin.png
      gethomepage.dev/name: pgAdmin 4
    hosts:
      - host: pgadmin4.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 256Mi
    advancedMounts:
      main: 
        main:
          - path: /var/lib/pgadmin
  
  servers:
    type: configMap
    name: pgadmin4
    advancedMounts:
      main: 
        main:
          - path: /pgadmin4/servers.json
            subPath: servers.json

configMaps:
  pgadmin4:
    enabled: true
    data:
      servers.json: |
        {
          "Servers": {
            "postgres-cluster": {
              "Group": "Servers",
              "Host": "postgresql-cluster-rw.database.svc.cluster.local",
              "MaintenanceDB": "postgres",
              "Name": "Local",
              "Port": 5432,
              "SSLMode": "prefer",
              "Username": "postgres"
            }
          }
        }
