# https://github.com/onedr0p/exportarr/
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-radarr
  namespace: monitoring
  labels:
    app: exporter-radarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: exporter-radarr
  template:
    metadata:
      labels:
        app: exporter-radarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: exporter-radarr
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          args:
            - radarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://radarr.servarr.svc.cluster.local:7878"
            - name: APIKEY
              value: "0416a6d418be4cd7b9b64e3862aa436a"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-radarr
  namespace: monitoring
  labels:
    app: exporter-radarr
spec:
  selector:
    app: exporter-radarr
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-radarr
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-radarr.monitoring.svc.cluster.local:9707
  metricsPath: /metrics
