---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  annotations:
    enable.version-checker.io/main: "true"
    match-regex.version-checker.io/main: ^v\d+\.\d+\.\d+$

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.0.1
        args: 
          - radarr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          PORT: "9707"
          URL: "http://radarr.servarr.svc.cluster.local:7878"
          APIKEY: "0416a6d418be4cd7b9b64e3862aa436a"

service:
  main:
    controller: main
    ports:
      http:
        port: 9707
    labels:
      instance: "exporter-radarr.monitoring.svc.cluster.local"

serviceMonitor:
  main:
    enabled: true
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
    targetLabels:
      - instance
