apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: mirror-testing-certificate
spec:
  source:
    name: testing-certificate
  destination:
    namespaces:
      - longhorn-system
