apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-radarr-restore
  namespace: database
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:15.5
          env:
            - name: INIT_POSTGRES_HOST
              value: "postgresql-cluster-rw.database.svc.cluster.local"
            - name: INIT_POSTGRES_USER
              value: "radarr"
            - name: INIT_POSTGRES_PASS
              value: "ReptileBubbleKissConversion"
            - name: INIT_POSTGRES_DBNAME
              value: "radarr-main radarr-logs"
            - name: INIT_POSTGRES_SUPER_PASS
              value: "TrembleBulwarkBeautifulGossip"
      containers:
        - name: restore-main
          image: bitnami/postgresql:16.1.0-debian-11-r15
          command:
            - /bin/sh
            - -ec
            - |
              zcat /backups/kubernetes/production/database/latest-pgsql_radarr-main_postgresql-cluster-rw.database.svc.cluster.local | /opt/bitnami/postgresql/bin/psql --host=$PGHOST --username=$PGUSER --dbname=$PGDATABASE
          volumeMounts:
            - mountPath: /backups
              name: backups
          env:
            - name: PGHOST
              value: "postgresql-cluster-rw.database.svc.cluster.local"
            - name: PGUSER
              value: "radarr"
            - name: PGPASSWORD
              value: "ReptileBubbleKissConversion"
            - name: PGDATABASE
              value: "radarr-main"
        - name: restore-logs
          image: bitnami/postgresql:16.1.0-debian-11-r15
          command:
            - /bin/sh
            - -ec
            - |
              zcat /backups/kubernetes/production/database/latest-pgsql_radarr-logs_postgresql-cluster-rw.database.svc.cluster.local | /opt/bitnami/postgresql/bin/psql --host=$PGHOST --username=$PGUSER --dbname=$PGDATABASE
          volumeMounts:
            - mountPath: /backups
              name: backups
          env:
            - name: PGHOST
              value: "postgresql-cluster-rw.database.svc.cluster.local"
            - name: PGUSER
              value: "radarr"
            - name: PGPASSWORD
              value: "ReptileBubbleKissConversion"
            - name: PGDATABASE
              value: "radarr-logs"
      volumes:
        - name: backups
          nfs:
            server: 192.168.35.30
            path: /mnt/tank/Media/Backups
      restartPolicy: Never
