apiVersion: v1
kind: ConfigMap
metadata:
  name: nut-config
  namespace: networking
data:
  ups.conf: | # Adjust this section as needed
    [OR1500LCDRT2U]
    driver = "snmp-ups"
    port = "rmcard205.internal.untouchedwagons.com"
    desc = "OR1500LCDRT2U"
    mibs = "cyberpower"
    community = "public"
  upsd.users: | # Adjust this section as needed
    [upsmon]
      password = NowGuideStandOwnJump
      upsmon slave
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nut
  namespace: networking
  labels:
    app: nut
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nut
  template:
    metadata:
      labels:
        app: nut
    spec:
      containers:
        - name: nut
          image: untouchedwagons/network-ups-tools:1.0.0
          volumeMounts:
            - mountPath: /etc/nut/ups.conf
              name: nut-config
              subPath: ups.conf
            - mountPath: /etc/nut/upsd.users
              name: nut-config
              subPath: upsd.users
      volumes:
        - name: nut-config
          configMap:
            name: nut-config
---
apiVersion: v1
kind: Service
metadata:
  name: nut
  namespace: networking
spec:
  type: LoadBalancer
  selector:
    app: nut
  ports:
    - name: nut
      targetPort: 3493
      port: 3493
