---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    fsGroup: 0
  annotations:
    enable.version-checker.io/main: "true"
    match-regex.version-checker.io/main: ^\d+\.\d+\.\d+$

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: vaultwarden/server
          tag: 1.31.0
        resources:
          limits:
            memory: 256Mi
            cpu: "500m"
          requests:
            memory: 64Mi
            cpu: "1m"

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Services
      gethomepage.dev/icon: bitwarden.png
      gethomepage.dev/name: Vaultwarden
    hosts:
      - host: vaultwarden.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 512Mi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: vaultwarden-config
    advancedMounts:
      main: 
        main:
          - path: /data
