---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    initContainers:
      restore:
        image:
          repository: untouchedwagons/simple-restore
          tag: 1.0.4
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/vaultwarden"
          BACKUP_BASE_NAME: "vaultwarden"

    containers:
      main:
        image:
          repository: vaultwarden/server
          tag: 1.30.0-alpine

      backup:
        image:
          repository: untouchedwagons/simple-backup
          tag: 1.0.5
        env:
          BACKUP_APPEND_DIRECTORY: "/kubernetes/production/vaultwarden"
          BACKUP_BASE_NAME: "vaultwarden"
          BACKUP_RETENTION: "24"
          BACKUP_FREQUENCY: "0 */8 * * *"

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Services
      gethomepage.dev/icon: bitwarden.png
      gethomepage.dev/name: Vaultwarden
    hosts:
      - host: vaultwarden.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 256Mi
    advancedMounts:
      main: 
        main:
          - path: /config
        backup:
          - path: /data
        restore:
          - path: /data

  nfs-backups:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Backups"
    advancedMounts:
      main: 
        backup:
          - path: /backups
        restore:
          - path: /backups
