---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  annotations:
    enable.version-checker.io/postgres-init: "true"
    enable.version-checker.io/main: "true"
    # match-regex.version-checker.io/main: ^\d+\.\d+\.\d+-alpine$
    use-sha.version-checker.io/main: "false"
    use-metadata.version-checker.io/main: "true"

controllers:
  main:
    strategy: Recreate

    initContainers:
      postgres-init:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 15.5
        env:
          INIT_POSTGRES_HOST: "postgresql-cluster-rw.database.svc.cluster.local"
          INIT_POSTGRES_USER: "vaultwarden"
          INIT_POSTGRES_PASS: "CrookScandalousLaurelMajestic"
          INIT_POSTGRES_DBNAME: "vaultwarden"
          INIT_POSTGRES_SUPER_PASS: "TrembleBulwarkBeautifulGossip"

    containers:
      main:
        image:
          repository: vaultwarden/server
          tag: 1.30.5
        env:
          DATABASE_URL: postgresql://vaultwarden:CrookScandalousLaurelMajestic@postgresql-cluster-rw.database.svc.cluster.local:5432/vaultwarden

service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Services
      gethomepage.dev/icon: bitwarden.png
      gethomepage.dev/name: Vaultwarden
    hosts:
      - host: vaultwarden.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services
