globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  replicas: 3

ports:
  web:
    redirectTo:
      port: websecure

ingressRoute:
  dashboard:
    annotations:
      kubernetes.io/ingress.class: traefik-external
    matchRule: Host(`traefik.services.untouchedwagons.com`)
    entryPoints: 
      - traefik
      - websecure
    tls:
      secretName: com-untouchedwagons-services

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false
