apiVersion: v1
kind: ConfigMap
metadata:
    name: ddclient
    namespace: networking
data:
    ddclient.conf: ENC[AES256_GCM,data:yXHkolmvCQP/3B+7x3l0tR3xZBiZqbxzDYDzM4T32UEDUHOe+d+5akAvbopSRmOmHXp1YokF/HIEMFrnSrny9S40UywV/Tp9ThrCvmzK6rssAKmkOJ8FnbJ92Y4csv06Y1QEYkjvPILNBSZaPx2F+zKzUad5M5U9BJ1lw1M8+hS1aAC4xCQW2Q9M1/+0rZxaE/g15IHFXlAlb4b5n3L+bzIYKfy0QHx8IgPbjW93FZv4jf3ylIAZ6gLqt0gHtCwfjtWoARYZk0uJJmYNWrZJtg4vlk59QEFcYloqNauugKMqQ6sv+qgAyiFJpZL8QPYdgiOXicTBhuxZpkdEdgYSWPwKZWMNw6M1P3f0Sa7Rf2/qB2kG95UVbv1CP6jaPQDx7jqUzUrx3m+cEj/dSWSw84iReV0g2vFthLkGACbnSS6mtpDVlScRGP5amTo7cdTcLyGKx8+4y4J90MilMC+z2i1I63XQQPkUM6F0NGtaskDuTe2KEsdGxS40NmVt4MXvPv15v/Fp0faspwAgDommYaoS3I7ywk0E/IbuAoyKSDh8YDjj46C+UDj8twWgcy6ROAFU/+A0ygCP97unZrVl6/NrqdeTA0C7bQiWzvTG5JeoKAj6ZBXk/c6I0SKDQn2+DCzA2GvCD5yq3P9zdq9vhNB2vJ0niOIwyLBsHdjAwKqDjQHV4uNCeAzeUhIZq9AixAc4wYA1uT5Tz7R42pikbkd8GPU1hw==,iv:pY8zJAh02kB8myxl/OUOCq7N9LKuK7cKotadIAw/co0=,tag:rjPvF0euDh6ji6pfbVaLaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbUkxeEw5Z2RoeWorWENq
            YTRtMlhXTFIvUFZyZlZDY0FOb0ZZUnhmd25vCi96OGJIbFRINWJJU2JneWRnS0d1
            QVBTT3R6SitRL3VyL044VXc3aUtUTE0KLS0tIFB4ZDRVMEt5THNrRWdXd1NmMXNL
            SHpKU2NqRGVGOURJVVZDYTRDSUt3cVUKXxIHaGUnL6P5TZ22cjSu0mPD25Fpu1Ze
            yEUhJu/YwKcfIvVgliFw+NHTZmH/M0/PJmgsWYj+IEPCDKYF+nyl1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T19:23:39Z"
    mac: ENC[AES256_GCM,data:kr180GAFDTCXrPx/3hhO4nJTF4j9Mu2Y/xKraRSp5gaOBDe5nqxAwXNLWyZR2GC8oSPkSRhyzs3jxJGHwX07m/5e1jfTCct328CizGcBIWJKvYo0tSCBLmAB37fxwR6iY3BaBzXY+l9/rkOKqRTv/sqLynRPVHoKMSJm6zSKprw=,iv:ZRpOJ4D0QyuXTTG0xFpiiXapZ9ooAr0SLVwQZr1Ubks=,tag:W5fBUmNVjEdyDCKoejZ1CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: ddclient
    namespace: networking
    labels:
        app: ddclient
spec:
    replicas: 1
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 0
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ddclient
    template:
        metadata:
            labels:
                app: ddclient
        spec:
            containers:
                - name: ddclient
                  image: matthewhuie/ddclient:2ea45fd
                  resources:
                    limits:
                        memory: 256Mi
                        cpu: "1"
                    requests:
                        memory: 64Mi
                        cpu: "0.1"
                  volumeMounts:
                    - mountPath: /etc/ddclient/ddclient.conf
                      name: ddclient-config
                      subPath: ddclient.conf
            volumes:
                - name: ddclient-config
                  configMap:
                    name: ddclient
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbUkxeEw5Z2RoeWorWENq
            YTRtMlhXTFIvUFZyZlZDY0FOb0ZZUnhmd25vCi96OGJIbFRINWJJU2JneWRnS0d1
            QVBTT3R6SitRL3VyL044VXc3aUtUTE0KLS0tIFB4ZDRVMEt5THNrRWdXd1NmMXNL
            SHpKU2NqRGVGOURJVVZDYTRDSUt3cVUKXxIHaGUnL6P5TZ22cjSu0mPD25Fpu1Ze
            yEUhJu/YwKcfIvVgliFw+NHTZmH/M0/PJmgsWYj+IEPCDKYF+nyl1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T19:23:39Z"
    mac: ENC[AES256_GCM,data:kr180GAFDTCXrPx/3hhO4nJTF4j9Mu2Y/xKraRSp5gaOBDe5nqxAwXNLWyZR2GC8oSPkSRhyzs3jxJGHwX07m/5e1jfTCct328CizGcBIWJKvYo0tSCBLmAB37fxwR6iY3BaBzXY+l9/rkOKqRTv/sqLynRPVHoKMSJm6zSKprw=,iv:ZRpOJ4D0QyuXTTG0xFpiiXapZ9ooAr0SLVwQZr1Ubks=,tag:W5fBUmNVjEdyDCKoejZ1CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0
