---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bazarr-config-backup
  namespace: servarr
spec:
  # The PVC to be backed up
  sourcePVC: bazarr-config
  trigger:
    # Take a backup every 8 hours
    schedule: "0 */8 * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: bazarr-config
    # Retention policy for backups
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    # Snapshot the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    storageClassName: ceph-block
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr-config-backup
  namespace: servarr
spec:
  sourcePVC: lidarr-config
  trigger:
    schedule: "0 */8 * * *"
  restic:
    pruneIntervalDays: 14
    repository: lidarr-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-config-backup
  namespace: servarr
spec:
  sourcePVC: prowlarr-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: prowlarr-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr-config-backup
  namespace: servarr
spec:
  sourcePVC: radarr-config
  trigger:
    schedule: "0 */8 * * *"
  restic:
    pruneIntervalDays: 14
    repository: radarr-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-config-backup
  namespace: servarr
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "0 */8 * * *"
  restic:
    pruneIntervalDays: 14
    repository: sonarr-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tdarr-server-config-backup
  namespace: servarr
spec:
  sourcePVC: tdarr-server-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: tdarr-server-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config-backup
  namespace: default
spec:
  sourcePVC: jellyfin-config
  trigger:
    schedule: "0 */8 * * *"
  restic:
    pruneIntervalDays: 14
    repository: jellyfin-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: qbittorrent-config-backup
  namespace: default
spec:
  sourcePVC: qbittorrent-config
  trigger:
    schedule: "0 */8 * * *"
  restic:
    pruneIntervalDays: 14
    repository: qbittorrent-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sabnzbd-config-backup
  namespace: default
spec:
  sourcePVC: sabnzbd-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: sabnzbd-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: file-browser-config-backup
  namespace: default
spec:
  sourcePVC: file-browser-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: file-browser-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ispyagentdvr-config-backup
  namespace: networking
spec:
  sourcePVC: ispyagentdvr-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: ispyagentdvr-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zwave-config-backup
  namespace: home-assistant
spec:
  sourcePVC: zwave-js-ui-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: zwave-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ha-config-backup
  namespace: home-assistant
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: ha-config
    retain:
      hourly: 4
      daily: 14
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
