---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zwave-js-ui
  namespace: home-assistant
  labels:
    app: zwave-js-ui
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zwave-js-ui
  template:
    metadata:
      labels:
        app: zwave-js-ui
    spec:
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
      securityContext:
        fsGroup: 568
      initContainers:
        - name: zwave-restore
          image: untouchedwagons/simple-restore:1.0.4
          volumeMounts:
            - mountPath: /data
              name: zwave-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/zwave"
            - name: BACKUP_BASE_NAME
              value: "zwave"
      containers:
        - name: zwave-js-ui
          image: ghcr.io/zwave-js/zwave-js-ui:9.8.2
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: "America/Toronto"
          volumeMounts:
            - mountPath: /usr/src/app/store
              name: zwave-config
            - mountPath: /dev/zwave0
              name: zwave-dongle

        - name: backup
          image: untouchedwagons/simple-backup:1.0.5
          volumeMounts:
            - mountPath: /data
              name: zwave-config
            - mountPath: /backups
              name: backups
          env:
            - name: BACKUP_APPEND_DIRECTORY
              value: "/kubernetes/production/zwave"
            - name: BACKUP_BASE_NAME
              value: "zwave"
            - name: BACKUP_RETENTION
              value: "7"
            - name: BACKUP_FREQUENCY
              value: "0 0 * * *"

      volumes:
        - name: zwave-config
          persistentVolumeClaim:
            claimName: zwave-config
        - name: backups
          nfs:
            server: 192.168.35.30
            path: /mnt/tank/Media/Backups
        - name: zwave-dongle
          hostPath: # Good lord that's a long path
            path: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_72a3599c46bcea11ab8496e368aed703-if00-port0
---
apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
  namespace: home-assistant
spec:
  selector:
    app: zwave-js-ui
  ports:
    - name: http
      targetPort: 8091
      port: 8091
    - name: websock
      targetPort: 3000
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwave-js-ui
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: zwavejs2mqtt.png
    gethomepage.dev/name: ZWave JS UI
spec:
  rules:
  - host: zwave.services.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: zwave-js-ui
            port:
              number: 8091
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-services
