---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/zwave-js/zwave-js-ui
          tag: 9.13.4
        env:
          TZ: "America/Toronto"
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 128Mi
            cpu: "5m"
          limits:
            memory: 256Mi
            cpu: "500m"

defaultPodOptions:
  nodeSelector:
    feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
  securityContext:
    fsGroup: 568

service:
  main:
    controller: main
    ports:
      http:
        port: 8091
      websocket:
        port: 3000

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Infrastructure
      gethomepage.dev/icon: zwavejs2mqtt.png
      gethomepage.dev/name: ZWave JS UI
    hosts:
      - host: zwave.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 128Mi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: zwave-config
    advancedMounts:
      main: 
        main:
          - path: /usr/src/app/store
  usb:
    type: hostPath
    hostPath: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_72a3599c46bcea11ab8496e368aed703-if00-port0
    globalMounts:
      - path: /dev/zwave0
