---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: zwave-config
