---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: servarr
  labels:
    app: radarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 30000
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:15.5
          env:
            - name: INIT_POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: INIT_POSTGRES_USER
              value: "radarr"
            - name: INIT_POSTGRES_PASS
              value: "ReptileBubbleKissConversion"
            - name: INIT_POSTGRES_DBNAME
              value: "radarr-main radarr-logs"
            - name: INIT_POSTGRES_SUPER_PASS
              value: "TrembleBulwarkBeautifulGossip"
      containers:
        - name: radarr
          image: ghcr.io/onedr0p/radarr:5.1.3.8246
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          env:
            - name: RADARR__API_KEY
              value: "0416a6d418be4cd7b9b64e3862aa436a"
            - name: RADARR__AUTHENTICATION_METHOD
              value: "Forms"
            - name: RADARR__AUTHENTICATION_REQUIRED
              value: "DisabledForLocalAddresses"
            - name: RADARR__POSTGRES_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: RADARR__POSTGRES_MAIN_DB
              value: "radarr-main"
            - name: RADARR__POSTGRES_LOG_DB
              value: "radarr-logs"
            - name: RADARR__POSTGRES_USER
              value: "radarr"
            - name: RADARR__POSTGRES_PASSWORD
              value: "ReptileBubbleKissConversion"
          resources:
            limits:
              memory: 1Gi
              cpu: "4"
            requests:
              memory: 512Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /mnt/data/Videos
              name: videos
            - mountPath: /mnt/data/Torrents
              name: torrents
            - mountPath: /mnt/data/Usenet
              name: usenet
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Backups
        - name: videos
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Videos
        - name: torrents
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Torrents
        - name: usenet
          nfs:
            server: 192.168.0.30
            path: /tank/Media/Usenet
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: servarr
spec:
  selector:
    app: radarr
  ports:
    - name: http
      targetPort: 7878
      port: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: servarr
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: radarr.services.internal.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: radarr
            port:
              number: 7878
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-internal-services