kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-proxmox
  namespace: monitoring
  labels:
    app: exporter-proxmox
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exporter-proxmox
  template:
    metadata:
      labels:
        app: exporter-proxmox
      annotations:
        enable.version-checker.io/main: "true"
        match-regex.version-checker.io/main: ^\d+\.\d+\.\d+$
    spec:
      containers:
        - name: exporter-proxmox
          image: prompve/prometheus-pve-exporter:3.4.2
          env:
            - name: PVE_USER
              value: "root@pam"
            - name: PVE_TOKEN_NAME
              value: "pve-exporter"
            - name: PVE_TOKEN_VALUE
              value: "019d4ad7-a1cc-4b45-ae02-02363f60f03e"
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-proxmox
  namespace: monitoring
spec:
  selector:
    app: exporter-proxmox
  ports:
    - name: http
      targetPort: 9221
      port: 9221
---
# If you're running a proxmox cluster this is all you need to do
# There's no need to scrape each node in the cluster
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-proxmox
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-proxmox.monitoring.svc.cluster.local:9221
  metricsPath: /pve
  params:
    target:
      - proxmox.internal.untouchedwagons.com
