---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bazarr-vol-restore
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: restore
        image: untouchedwagons/simple-restore:1.0.2
        volumeMounts:
          - mountPath: /data
            name: bazarr-config
          - mountPath: /backups
            name: backups
        env:
          - name: BACKUP_APPEND_DIRECTORY
            value: "/kubernetes/production/bazarr"
          - name: BACKUP_BASE_NAME
            value: "bazarr"
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: backups
          nfs:
            server: 192.168.0.30
            path: /mnt/tank/Media/Backups
      restartPolicy: Never