# https://github.com/onedr0p/exportarr/
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr-exporter
  namespace: monitoring-exportarr
  labels:
    app: radarr-exportarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: radarr-exportarr
  template:
    metadata:
      labels:
        app: radarr-exportarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: radarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          args:
            - radarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://radarr.servarr.svc.cluster.local:7878"
            - name: APIKEY
              value: "0416a6d418be4cd7b9b64e3862aa436a"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-exportarr
  namespace: monitoring-exportarr
  labels:
    app: radarr-exportarr
spec:
  selector:
    app: radarr-exportarr
  ports:
    - name: monitoring
      port: 9707
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: radarr
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - radarr-exportarr.monitoring-exportarr.svc.cluster.local:9707
  metricsPath: /metrics
