# https://github.com/esanchezm/prometheus-qbittorrent-exporter
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent-exporter
  namespace: monitoring-exportarr
  labels:
    app: qbittorrent-exportarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: qbittorrent-exportarr
  template:
    metadata:
      labels:
        app: qbittorrent-exportarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: qbittorrent-exporter
          image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
          env:
            - name: QBITTORRENT_HOST
              value: "qbittorrent.default.svc.cluster.local"
            - name: QBITTORRENT_PORT
              value: "8080"
            - name: QBITTORRENT_USER
              value: "admin"
            - name: QBITTORRENT_PASS
              value: "adminadmin"
            - name: EXPORTER_PORT
              value: "9707"
            - name: VERIFY_WEBUI_CERTIFICATE
              value: "False"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-exportarr
  namespace: monitoring-exportarr
  labels:
    app: qbittorrent-exportarr
spec:
  selector:
    app: qbittorrent-exportarr
  ports:
    - name: monitoring
      port: 9707
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: qbittorrent
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - qbittorrent-exportarr.monitoring-exportarr.svc.cluster.local:9707
  metricsPath: /metrics
