{
 "title": "Blackbox Exporter",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", module=\"http_2xx\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", module=\"http_2xx\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", module=\"http_2xx\"}"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", module=\"http_2xx\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", module=\"http_2xx\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", module=\"http_2xx\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", module=\"http_2xx\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", module=\"http_2xx\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration ($instance)",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Phases Duration ($instance)",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}