{
 "title": "K8s / Resources",
 "description": "The dashboard offers a simple view of the resource consumption of the deployed pods and their impact on the cluster. The outline of requests and limits for each pod and their totals can be used as a tool to determine appropriate resource quotas for your cluster.",
 "tags": [
  "k8s",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Restarted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{ namespace = \"$namespace\" })",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{ namespace = \"$namespace\" }) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\", namespace = \"$namespace\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{image!=\"\", namespace = \"$namespace\"}) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\", namespace = \"$namespace\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", namespace = \"$namespace\"}) by (pod)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{name!=\"\", namespace = \"$namespace\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_info {namespace = \"$namespace\"}) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\", namespace = \"$namespace\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", namespace = \"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace = \"$namespace\"}[5m])) by (pod)"
    },
    {
     "expr": "max(kube_pod_info {namespace = \"$namespace\"}) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"POD\", namespace = \"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (mcores)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace = \"$namespace\"}[5m]) * 1000) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}