{
 "title": "K8s / Storage",
 "description": "Dashboard of Kubernetes / OpenShift volume information at namespace level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "k8s",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info,namespace)"
    }
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   },
   {
    "name": "persistentvolumeclaim",
    "query": "label_values(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n count (\n   (kubelet_volume_stats_available_bytes {namespace=\"$namespace\"})\n   and\n   (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_unbound_pvc_count {exported_namespace = \"$namespace\"}))) or (vector(0))"
    }
   ]
  },
  {
   "title": "Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_bound_pvc_count {exported_namespace = \"$namespace\", service=\"kube-prometheus-stack-kube-etcd\"}))) or (vector(0))"
    }
   ]
  },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate - Current",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  (\n    (kubelet_volume_stats_available_bytes {namespace=\"$namespace\"} ) \n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\"}[1w], 7 * 24 * 60 * 60) < 0)\n  )\n)"
    }
   ]
  },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate -  Predicted Available Space History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  (kube_persistentvolumeclaim_info {namespace=\"$namespace\"})\n  and\n  (\n    (\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}))\n      /\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"}))\n    ) >= ($pvc_percent_used_warning_threshold / 100)\n  )\n)"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100)"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"}))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)"
    }
   ]
  },
  {
   "title": "PVC Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\" })"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\" })"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes { namespace = \"$namespace\" })"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\" })) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\" }))"
    }
   ]
  },
  {
   "title": "Hourly Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}[1h])",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}[1d])",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}[1w])",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "$persistentvolumeclaim",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "repeat": "persistentvolumeclaim",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}))",
     "legendFormat": "Capacity"
    }
   ]
  }
 ]
}