{
 "title": "K8S / Nodes",
 "description": "An overview of all nodes within the clusters. Relies on data from kube-state-metrics and node-exporter",
 "tags": [ "k8s" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Top", "query": "1, 3, 5, 10, 20, 50, 100" },
   { "name": "Step", "query": "30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(max(node_cpu_seconds_total{container=\"node-exporter\"}) without (mode)) without (cpu))"
    }
   ]
  },
  {
   "title": "Time Since Last Reboot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - topk(1, node_boot_time_seconds{container=\"node-exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Total Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Total Filesystem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!=\"tmpfs\", container=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Total Active CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|guest.*\", container=\"node-exporter\"}[15m]))"
    }
   ]
  },
  {
   "title": "Total Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load15{container=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info) - count(kube_node_role{role=\"master\"})"
    }
   ]
  },
  {
   "title": "Not Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_node_status_condition{condition=\"Ready\", status!=\"true\"}) without (condition, status) > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Active Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_memory_Active_bytes)" }
   ]
  },
  {
   "title": "Total Used Filesystem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes - node_filesystem_avail_bytes{fstype!=\"tmpfs\", container=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load (Relative to Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($Top, node_load5 / count(max(node_cpu_seconds_total{container=\"node-exporter\"}) without (mode)) without (cpu))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Relative to Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($Top, sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|guest.*\", container=\"node-exporter\"}[5m])) without (cpu, mode) / count(max(node_cpu_seconds_total) without (mode)) without (cpu))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) / count(max(node_cpu_seconds_total) without (mode)) by (node)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "count(max(node_cpu_seconds_total) without (mode)) by (node) - sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Load (Absolute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "topk($Top, node_load5{container=\"node-exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Absolute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "topk($Top, sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|guest.*\", container=\"node-exporter\"}[5m])) without (cpu, mode))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (node) / count(max(node_cpu_seconds_total) without (mode)) by (node)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unavailable Memory (Relative to Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($Top, 1 - node_memory_MemAvailable_bytes{container=\"node-exporter\"} / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Used Memory (Relative to Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($Top, (node_memory_Buffers_bytes{container=\"node-exporter\"} + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node) / ON(node) GROUP_LEFT kube_node_status_allocatable{resource=\"memory\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\"} - ON(node) GROUP_RIGHT sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Unavailable Memory (Absolute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($Top, node_memory_MemTotal_bytes{container=\"node-exporter\"} - node_memory_MemAvailable_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Used Memory (Absolute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($Top, node_memory_MemTotal_bytes{container=\"node-exporter\"} - (node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (node) / ON(node) GROUP_LEFT kube_node_status_allocatable{resource=\"memory\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Pods",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, kubelet_running_containers{container_state=\"running\", service=\"kube-prometheus-stack-kubelet\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Scheduling Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kubelet_runtime_operations_total{operation_type=~\"(stop|remove|start|run|update|create)_.+\"}[5m])) by (node))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Saturation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($Top, 1-node_filesystem_avail_bytes/node_filesystem_size_bytes{device!=\"tmpfs\",fstype=\"vfat\",container=\"node-exporter\"})",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($Top, rate(node_disk_io_time_weighted_seconds_total{container=\"node-exporter\"}[5m]))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Filesystem Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($Top, rate(node_disk_read_bytes_total{container=\"node-exporter\"}[5m]))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($Top, node_filesystem_size_bytes - node_filesystem_avail_bytes{device!=\"tmpfs\", device!=\"shm\", device!=\"ramfs\", container=\"node-exporter\"})",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "File Descriptor Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($Top, node_filefd_allocated{container=\"node-exporter\"} / node_filefd_maximum)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($Top, rate(node_disk_written_bytes_total{container=\"node-exporter\"}[5m]))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic - Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"^(ens|eno)[1-9]+[0-9]*|eth[0-9]+|enp[0-9]+s[0-9]+$\", container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Packets Dropped - Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bad Packets - Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total{container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic - Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"^(ens|eno)[1-9]+[0-9]*|eth[0-9]+|enp[0-9]+s[0-9]+$\", container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Packets Dropped - Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_drop_total{container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bad Packets - Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_errs_total{container=\"node-exporter\"}[5m])) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}