{
 "title": "Qbittorrent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "categories",
    "label": "Categories",
    "query": {
     "query": "label_values(qbittorrent_torrents_count, category)"
    }
   },
   { "name": "data_source", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Qbittorrent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "qbittorrent_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bittorrent network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_firewalled", "legendFormat": "Status" }
   ]
  },
  {
   "title": "DHT nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_dht_nodes", "legendFormat": "DHT nodes" }
   ]
  },
  {
   "title": "Data downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_dl_info_data_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Data uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_up_info_data_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Accumulated ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (qbittorrent_up_info_data_total)) / (sum by (app) (qbittorrent_dl_info_data_total))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_up_info_data_total[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transfer Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total[2m])",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(qbittorrent_up_info_data_total[2m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents by status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\", status!=\"complete\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Torrents by categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\",status!=\"complete\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}