{
 "title": "Technitium",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total queries received",
   "type": "stat",
   "description": "The total number of queries the DNS server has received from all clients.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_total_queries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Domains",
   "type": "table",
   "description": "Top allowed domains",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(technitium_top_domains)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries resolved via cache",
   "type": "stat",
   "description": "The total number of queries that were resolved using data available in the server's cache.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_cached_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authoritative queries resolved",
   "type": "stat",
   "description": "The total number of queries that were resolved from the zones hosted locally on the DNS server.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_total_authoritative", "legendFormat": "__auto" }
   ]
  },
  { "title": "Domain blocking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Block List Zone count",
   "type": "stat",
   "description": "Number of domain names listed in blocked zones",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_block_list_zones", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "description": "Top blocked domains",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc(technitium_top_blocked_domains)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allowed Zone count",
   "type": "stat",
   "description": "Allowed zones allows to add exception to unblock domain names listed in blocked zones",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_allowed_zones", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total queries blocked",
   "type": "stat",
   "description": "The total number of queries this DNS server blocked by responding with \"0.0.0.0\" (or \"::\" for AAAA) for A record request.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_total_blocked", "legendFormat": "__auto" }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Client count",
   "type": "stat",
   "description": "The total number of unique clients based on IP address of the queries.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technitium_total_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "description": "Top clients total requests",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 27 },
   "targets": [
    {
     "expr": "sort_desc(sum by (host) (technitium_top_clients))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}