{
 "title": "ZFS",
 "description": "ZFS Zpool metrics as produced byhttps://github.com/pdf/zfs_exporter",
 "tags": [
  "zfs ",
  "storage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(zfs_pool_health,instance)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zfs_pool_health{instance=\"$instance\"},pool)"
    }
   },
   {
    "name": "dataset",
    "query": {
     "query": "label_values(zfs_dataset_used_by_dataset_bytes{instance=\"$instance\", pool=\"$pool\", type=\"filesystem\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pool Pool health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_health{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "{{pool}}  pool state"
    }
   ]
  },
  {
   "title": "$pool Pool read-only",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_readonly{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "{{pool}}  pool state"
    }
   ]
  },
  {
   "title": "$pool Pool size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_size_bytes{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$pool Pool free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_free_bytes{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$pool Pool fragmented",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_fragmentation_ratio{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataset state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$instance:$dataset Pool Space",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_dataset_used_bytes{instance=\"$instance\", pool=\"$pool\", name=\"$dataset\"} ",
     "legendFormat": "{{name}} dataset used"
    },
    {
     "expr": "zfs_dataset_available_bytes{instance=\"$instance\", pool=\"$pool\", name=\"$dataset\"} ",
     "legendFormat": "{{name}} dataset available"
    }
   ]
  },
  {
   "title": "Dataset quota",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_dataset_quota_bytes{instance=\"$instance\", pool=\"$pool\", name=\"$dataset\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}