# https://github.com/onedr0p/exportarr/
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-sonarr
  namespace: monitoring
  labels:
    app: exporter-sonarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: exporter-sonarr
  template:
    metadata:
      labels:
        app: exporter-sonarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: sonarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.6.2
          args:
            - sonarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://sonarr.servarr.svc.cluster.local:8989"
            - name: APIKEY
              value: "0fe183143c5745269ae3b9ea163c8f85"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-sonarr
  namespace: monitoring
  labels:
    app: exporter-sonarr
spec:
  selector:
    app: exporter-sonarr
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-sonarr
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - exporter-sonarr.monitoring.svc.cluster.local:9707
  metricsPath: /metrics
