
cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "ceph-test-1"
        devices:
          - name: "/dev/vdb"
      - name: "ceph-test-2"
        devices:
          - name: "/dev/vdb"
      - name: "ceph-test-3"
        devices:
          - name: "/dev/vdb"

ingress:
  # -- Enable an ingress for the ceph-dashboard
  dashboard:
    annotations:
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    host:
      name: ceph.testing.untouchedwagons.com
      path: /
    tls:
      - hosts:
        - untouchedwagons.com
        secretName: testing-certificate
