---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: &app homepage
  namespace: default
  labels:
    app: *app
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      serviceAccountName: *app
      automountServiceAccountToken: true
      enableServiceLinks: true
      containers:
        - name: *app
          image: ghcr.io/gethomepage/homepage:v0.8.10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 256Mi
              cpu: "2"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /app/config
              name: homepage-config
            - mountPath: /app/config/logs
              name: logs

      volumes:
        - name: homepage-config
          configMap:
              name: homepage
        - name: logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  selector:
    app: homepage
  ports:
    - name: http
      targetPort: 3000
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: services.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-services
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: default
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: |
      mode: cluster
    settings.yaml: |
        ---
        # For configuration options and examples, please see:
        # https://gethomepage.dev/en/configs/settings

        layout:
          Bookmarks:
            style: row
            columns: 3
          Multimedia:
            style: row
            columns: 3
          Download Clients:
            style: row
            columns: 2
          Infrastructure:
            style: row
            columns: 3
          Networking & Equipment:
            style: row
            columns: 3
          Security:
            style: row
            columns: 3
          Services:
            style: row
            columns: 3
          Monitoring:
            style: row
            columns: 3
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ""
    services.yaml: |
        - Bookmarks:
            - Reddit:
                icon: reddit.png
                href: https://reddit.com
            - YouTube:
                icon: youtube.png
                href: https://youtube.com
            - Mastodon:
                icon: mastodon.png
                href: https://mstdn.ca
            - Github:
                icon: github.png
                href: https://github.com
            - BlueSky:
                icon: si-bluesky-#0285FF
                href: https://bsky.app
            - Lemmy:
                icon: lemmy.png
                href: https://lemmy.ca

        - Multimedia: []

        - Download Clients: []

        - Security:
            - Front door camera:
                icon: mdi-cctv
                href: https://Camera-Front-Door.internal.untouchedwagons.com
            - Side door camera:
                icon: mdi-cctv
                href: https://Camera-Side-Door.internal.untouchedwagons.com
            - ISpyAgent DVR:
                icon: ispy.png
                href: http://192.168.35.53

        - Networking & Equipment:
            - Home Hub 3000:
                icon: mdi-router-wireless
                href: https://192.168.10.1
            - OPNSense:
                icon: opnsense.png
                href: http://opnsense.internal.untouchedwagons.com
            - Unifi:
                icon: unifi.png
                href: https://unifi.internal.untouchedwagons.com:8443
            - UPS Remote Management Card:
                icon: mdi-car-battery
                href: http://rmcard205.internal.untouchedwagons.com
            - Dell R220 iDRAC:
                icon: idrac.png
                href: https://idrac-cjtyp22.internal.untouchedwagons.com
            - Dell R420 iDRAC:
                icon: idrac.png
                href: https://idrac-7p57cz1.internal.untouchedwagons.com
            - Dell R630 iDRAC:
                icon: idrac.png
                href: https://idrac-CZBLPD2.internal.untouchedwagons.com
            - Dell R730XD iDRAC:
                icon: idrac.png
                href: https://idrac-jnky182.internal.untouchedwagons.com

        - Infrastructure:
            - Proxmox:
                icon: proxmox.png
                href: https://pve.internal.untouchedwagons.com:8006
                widget:
                  type: proxmox
                  url: https://pve.internal.untouchedwagons.com:8006
                  username: root@pam!pve-exporter
                  password: ac4d0a24-cafa-4174-81ba-a24a05b3d9c2
            - Proxmox Backup Server:
                icon: proxmox.png
                href: https://vault.internal.untouchedwagons.com:8007
                widget:
                  type: proxmoxbackupserver
                  url: https://vault.internal.untouchedwagons.com:8007
                  username: root@pam!homepage
                  password: a68b0d0f-a97b-4c57-9025-a54758686405
            - Traefik:
                icon: traefik.png
                href: https://traefik.services.untouchedwagons.com
                widget:
                  type: traefik
                  url: https://traefik.services.untouchedwagons.com
            - Ceph:
                icon: ceph.png
                href: https://ceph.services.untouchedwagons.com
            - Netboot.XYZ:
                icon: netboot.png
                href: http://netboot.internal.untouchedwagons.com
            - Technitium:
                icon: technitium.png
                href: http://technitium.internal.untouchedwagons.com

        - Services: []

        - Monitoring: []

    widgets.yaml: |
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              # Shows cluster-wide statistics
              show: true
              # Shows the aggregate CPU stats
              cpu: true
              # Shows the aggregate memory stats
              memory: true
              # Shows a custom label
              showLabel: true
              label: "cluster"
            nodes:
              # Shows node-specific statistics
              show: true
              # Shows the CPU for each node
              cpu: true
              # Shows the memory for each node
              memory: true
              # Shows the label, which is always the node name
              showLabel: true
    docker.yaml: ""
