---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v0.8.9
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 256Mi
              cpu: "2"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /app/config
              name: homepage-config
            - mountPath: /app/config/logs
              name: logs

      volumes:
        - name: homepage-config
          configMap:
              name: homepage
        - name: logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  selector:
    app: homepage
  ports:
    - name: http
      targetPort: 3000
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: services.untouchedwagons.com
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
    - hosts: 
      - untouchedwagons.com
      secretName: com-untouchedwagons-services
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: default
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: ""
    settings.yaml: |
        ---
        # For configuration options and examples, please see:
        # https://gethomepage.dev/en/configs/settings

        layout:
          Bookmarks:
            style: row
            columns: 3
          Multimedia:
            style: row
            columns: 3
          Download Clients:
            style: row
            columns: 2
          Infrastructure:
            style: row
            columns: 3
          Networking & Equipment:
            style: row
            columns: 3
          Security:
            style: row
            columns: 3
          Services:
            style: row
            columns: 3
          Monitoring:
            style: row
            columns: 3
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ""
    services.yaml: |
        - Bookmarks:
            - Reddit:
                icon: reddit.png
                href: https://reddit.com
            - YouTube:
                icon: youtube.png
                href: https://youtube.com
            - Twitter:
                icon: twitter.png
                href: https://twitter.com
            - Mastodon:
                icon: mastodon.png
                href: https://mstdn.ca
            - Github:
                icon: github.png
                href: https://github.com
            - BlueSky:
                icon: bluesky.png
                href: https://bsky.app
        - Multimedia:
            - Sonarr:
                icon: sonarr.png
                href: https://sonarr.services.untouchedwagons.com
                widget:
                  type: sonarr
                  url: https://sonarr.services.untouchedwagons.com
                  key: 0fe183143c5745269ae3b9ea163c8f85
            - Radarr:
                icon: radarr.png
                href: https://radarr.services.untouchedwagons.com
                widget:
                  type: radarr
                  url: https://radarr.services.untouchedwagons.com
                  key: 0416a6d418be4cd7b9b64e3862aa436a
            - Prowlarr:
                icon: prowlarr.png
                href: https://prowlarr.services.untouchedwagons.com
                widget:
                  type: prowlarr
                  url: https://prowlarr.services.untouchedwagons.com
                  key: fa88672ddbeb4b5683a009951076bf38
            - Bazarr:
                icon: bazarr.png
                href: https://bazarr.services.untouchedwagons.com
                widget:
                  type: bazarr
                  url: https://bazarr.services.untouchedwagons.com
                  key: b9f8668f49e13b76f2c872e5bcaf2048
            - Lidarr:
                icon: lidarr.png
                href: https://lidarr.services.untouchedwagons.com
                widget:
                  type: lidarr
                  url: https://lidarr.services.untouchedwagons.com
                  key: 1555da6d78404bffb22c90ace2b31b31
            - Jellyfin:
                icon: jellyfin.png
                href: https://jellyfin.services.untouchedwagons.com
                widget:
                    type: jellyfin
                    url: https://jellyfin.services.untouchedwagons.com
                    key: c8f345d99d1a47eba3eef1a75c946516

        - Download Clients:
            - qBitTorrent:
                icon: qbittorrent.png
                href: https://qbittorrent.services.untouchedwagons.com
                widget:
                  type: qbittorrent
                  url: https://qbittorrent.services.untouchedwagons.com
            - SABnzbd:
                icon: sabnzbd.png
                href: https://sabnzbd.services.untouchedwagons.com
                widget:
                  type: sabnzbd
                  url: https://sabnzbd.services.untouchedwagons.com
                  key: 441c51b1799e551d7b4757b179fe7e96

        - Security:
            - Front door camera:
                icon: mdi-cctv
                href: https://Camera-Front-Door.internal.untouchedwagons.com
            - Side door camera:
                icon: mdi-cctv
                href: https://Camera-Side-Door.internal.untouchedwagons.com
            - ISpyAgent DVR:
                icon: ispy.png
                href: http://192.168.35.53

        - Networking & Equipment:
            - Home Hub 3000:
                icon: mdi-router-wireless
                href: https://192.168.10.1
            - OPNSense:
                icon: opnsense.png
                href: http://opnsense.internal.untouchedwagons.com
            - Unifi:
                icon: unifi.png
                href: https://unifi.internal.untouchedwagons.com:8443
            - UPS Remote Management Card:
                icon: mdi-car-battery
                href: http://rmcard205.internal.untouchedwagons.com
            - Dell R220 iDRAC:
                icon: idrac.png
                href: https://idrac-cjtyp22.internal.untouchedwagons.com
            - Dell R420 iDRAC:
                icon: idrac.png
                href: https://idrac-7p57cz1.internal.untouchedwagons.com
            - Dell R630 iDRAC:
                icon: idrac.png
                href: https://idrac-CZBLPD2.internal.untouchedwagons.com
            - Dell R730XD iDRAC:
                icon: idrac.png
                href: https://idrac-jnky182.internal.untouchedwagons.com

        - Infrastructure:
            - Proxmox:
                icon: proxmox.png
                href: https://pve.internal.untouchedwagons.com:8006
                # widget:
                #     type: proxmox
                #     url: https://pve-node-01.internal.untouchedwagons.com:8006
                #     username: api@pam!homepage
                #     password: 2041a948-ba79-44ed-b0ce-e9a5300cbc42
            - Proxmox Backup Server:
                icon: proxmox.png
                href: https://vault.internal.untouchedwagons.com:8007
                # widget:
                #   type: proxmoxbackupserver
                #   url: https://vault.internal.untouchedwagons.com:8007
                #   username: root@pam!homepage
                #   password: a68b0d0f-a97b-4c57-9025-a54758686405
            - Home Assistant:
                icon: home-assistant.png
                href: https://home-assistant.services.untouchedwagons.com
            - Traefik:
                icon: traefik.png
                href: https://traefik.services.untouchedwagons.com
                widget:
                  type: traefik
                  url: https://traefik.services.untouchedwagons.com
            - Ceph:
                icon: ceph.png
                href: https://ceph.services.untouchedwagons.com
            - Netboot.XYZ:
                icon: netboot.png
                href: http://netboot.internal.untouchedwagons.com
            - Technitium:
                icon: technitium.png
                href: http://technitium.internal.untouchedwagons.com
            - ZWave JS UI:
                icon: zwavejs2mqtt.png
                href: https://zwave.services.untouchedwagons.com

        - Services:
            - Vaultwarden:
                icon: bitwarden.png
                href: https://vaultwarden.services.untouchedwagons.com
            - IT Tools:
                icon: it-tools.png
                href: https://it-tools.services.untouchedwagons.com
            - pgAdmin 4:
                icon: pgadmin.png
                href: https://pgadmin4.services.untouchedwagons.com
            - Tdarr:
                icon: tdarr.png
                href: https://tdarr.services.untouchedwagons.com
            - File Browser:
                icon: filebrowser.png
                href: https://file-browser.services.untouchedwagons.com

        - Monitoring:
            - Grafana:
                icon: grafana.png
                href: https://grafana.services.untouchedwagons.com
            - Prometheus:
                icon: prometheus.png
                href: https://prometheus.services.untouchedwagons.com
            - Alert Manager:
                icon: alertmanager.png
                href: https://alertmanager.services.untouchedwagons.com

    widgets.yaml: |
        - search:
            provider: duckduckgo
            target: _blank
    docker.yaml: ""
