---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: jellyfin/jellyfin
          tag: 10.9.5
        resources:
          limits:
            memory: 2048Mi
            cpu: "2"
          requests:
            memory: 1024Mi
            cpu: "10m"

service:
  main:
    controller: main
    ports:
      http:
        port: 8096

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Multimedia
      gethomepage.dev/icon: jellyfin.png
      gethomepage.dev/name: Jellyfin
      gethomepage.dev/widget.type: "jellyfin"
      gethomepage.dev/widget.url: "https://jellyfin.testing.untouchedwagons.com"
      gethomepage.dev/widget.key: "c8f345d99d1a47eba3eef1a75c946516"
    hosts:
      - host: jellyfin.testing.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-testing

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      main: 
        main:
          - path: /config

  tmp:
    type: emptyDir
    advancedMounts:
      main: 
        main:
          - path: /config/transcodes

  nfs-music:
    type: "nfs"
    server: "192.168.20.30"
    path: "/mnt/tank/Media/Music"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Music

  nfs-videos:
    type: "nfs"
    server: "192.168.20.30"
    path: "/mnt/tank/Media/Videos"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Videos
