---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    fsGroup: 568

controllers:
  main:
    strategy: Recreate

    initContainers:
      postgres-init:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 15.5
        env:
          INIT_POSTGRES_HOST: "postgresql-cluster-rw.database.svc.cluster.local"
          INIT_POSTGRES_USER: "sonarr"
          INIT_POSTGRES_PASS: "AuthorizeBrazenWakenVerify"
          INIT_POSTGRES_DBNAME: "sonarr-main sonarr-logs"
          INIT_POSTGRES_SUPER_PASS: "TrembleBulwarkBeautifulGossip"

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sonarr
          tag: 4.0.5.1710
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          SONARR__API_KEY: "0fe183143c5745269ae3b9ea163c8f85"
          SONARR__AUTHENTICATION_METHOD: "Forms"
          SONARR__AUTHENTICATION_REQUIRED: "DisabledForLocalAddresses"
          SONARR__POSTGRES_HOST: "postgresql-cluster-rw.database.svc.cluster.local"
          SONARR__POSTGRES_MAIN_DB: "sonarr-main"
          SONARR__POSTGRES_LOG_DB: "sonarr-logs"
          SONARR__POSTGRES_USER: "sonarr"
          SONARR__POSTGRES_PASSWORD: "AuthorizeBrazenWakenVerify"
        resources:
          requests:
            memory: 128Mi
            cpu: "10m"
          limits:
            memory: 1024Mi
            cpu: "2"

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

ingress:
  main:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Multimedia
      gethomepage.dev/icon: sonarr.png
      gethomepage.dev/name: Sonarr
      gethomepage.dev/widget.type: "sonarr"
      gethomepage.dev/widget.url: "https://sonarr.services.untouchedwagons.com"
      gethomepage.dev/widget.key: "0fe183143c5745269ae3b9ea163c8f85"
    hosts:
      - host: sonarr.services.untouchedwagons.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: 
        - untouchedwagons.com
        secretName: com-untouchedwagons-services

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    dataSourceRef:
      kind: ReplicationDestination
      apiGroup: volsync.backube
      name: sonarr-config
    advancedMounts:
      main: 
        main:
          - path: /config
        restore:
          - path: /data

  nfs-videos:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Videos"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Videos

  nfs-torrents:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Torrents"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Torrents

  nfs-usenet:
    type: "nfs"
    server: "192.168.35.30"
    path: "/mnt/tank/Media/Usenet"
    advancedMounts:
      main: 
        main:
          - path: /mnt/data/Usenet

