apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-exporter
  namespace: monitoring
spec:
  relabelings:
    - action: replace
      replacement: 'pve-node-01.internal.untouchedwagons.com'
      targetLabel: instance
  staticConfigs:
    - targets:
        - proxmox-exporter.monitoring-proxmox.svc.cluster.local:9221
  metricsPath: /pve
  params:
    target:
      - pve-node-01.internal.untouchedwagons.com
