# https://github.com/onedr0p/exportarr/
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-bazarr
  namespace: monitoring
  labels:
    app: exporter-bazarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: exporter-bazarr
  template:
    metadata:
      labels:
        app: exporter-bazarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9707"
    spec:
      containers:
        - name: exporter-bazarr
          image: ghcr.io/onedr0p/exportarr:v1.6.2
          args:
            - bazarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://bazarr.servarr.svc.cluster.local:6767"
            - name: APIKEY
              value: "b9f8668f49e13b76f2c872e5bcaf2048"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-bazarr
  namespace: monitoring
  labels:
    app: exporter-bazarr
spec:
  selector:
    app: exporter-bazarr
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-bazarr
  namespace: monitoring
spec:
  scrapeTimeout: 20s
  staticConfigs:
    - targets:
        - exporter-bazarr.monitoring.svc.cluster.local:9707
  metricsPath: /metrics
