crds:
    enabled: true
cleanPrometheusOperatorObjectNames: true
alertmanager:
    config:
        route:
            routes:
                - receiver: "null"
                  match:
                    severity: email
                  group_wait: 10s
                  repeat_interval: 1m
        receivers:
            - name: "null"
              pushover_configs:
                - user_key: ENC[AES256_GCM,data:2lngdheeAfltXhAjNYN2sW+cBzj2qBgteYm+/a5g,iv:zeitBTxSXhUyhZ2fWSMe2FfnAq9VxupslenyaYHnAOU=,tag:d97ZU+92NqYK90rBukuGUQ==,type:str]
                  token: ENC[AES256_GCM,data:1kvCqDwK1n+2wJRgcBvwS9kS9V0QVXkZovMw//Oq,iv:uLSiK0o9kCwGuSfjL7ybnx08o7i+sXMcIynQEPxZDZg=,tag:nfA+GFNleT+WHnjouGVrmw==,type:str]
    ingress:
        enabled: true
        hosts:
            - alertmanager.services.untouchedwagons.com
        tls:
            - secretName: com-untouchedwagons-services
              hosts:
                - alertmanager.services.untouchedwagons.com
kube-state-metrics:
    metricLabelsAllowlist:
        - deployments=[*]
        - persistentvolumeclaims=[*]
        - pods=[*]
    prometheus:
        monitor:
            enabled: true
            relabelings:
                - action: replace
                  sourceLabels:
                    - __meta_kubernetes_pod_node_name
                  regex: ^(.*)$
                  replacement: $1
                  targetLabel: kubernetes_node
prometheus-node-exporter:
    prometheus:
        monitor:
            enabled: true
            relabelings:
                - action: replace
                  regex: ^(.*)$
                  replacement: $1
                  sourceLabels:
                    - __meta_kubernetes_endpoint_node_name
                  targetLabel: instance
kubelet:
    enabled: true
    serviceMonitor:
        metricRelabelings:
            # Remove duplicate labels provided by k3s
            - action: keep
              sourceLabels:
                - __name__
              regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)
            - action: replace
              sourceLabels:
                - node
              targetLabel: instance
            # Drop high cardinality labels
            - action: labeldrop
              regex: (uid)
            - action: labeldrop
              regex: (id|name)
            - action: drop
              sourceLabels:
                - __name__
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
kubeApiServer:
    enabled: true
    serviceMonitor:
        metricRelabelings:
            # Remove duplicate labels provided by k3s
            - action: keep
              sourceLabels:
                - __name__
              regex: (aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)
            # Drop high cardinality labels
            - action: drop
              sourceLabels:
                - __name__
              regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
            - action: drop
              sourceLabels:
                - __name__
              regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)
kubeControllerManager:
    enabled: true
    serviceMonitor:
        metricRelabelings:
            # Remove duplicate labels provided by k3s
            - action: keep
              sourceLabels:
                - __name__
              regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|attachdetach_controller|authenticated_user|authentication|cronjob_controller|disabled_metric|endpoint_slice|ephemeral_volume|garbagecollector_controller|get_token|go|hidden_metric|job_controller|kubernetes_build|kubernetes_feature|leader_election|node_collector|node_ipam|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|pv_collector|registered_metric|replicaset_controller|rest_client|retroactive_storageclass|root_ca|running_managed|scrape_duration|scrape_samples|scrape_series|service_controller|storage_count|storage_operation|ttl_after|volume_operation|workqueue)_(.+)
kubeEtcd:
    enabled: true
kubeScheduler:
    enabled: true
    serviceMonitor:
        metricRelabelings:
            # Remove duplicate labels provided by k3s
            - action: keep
              sourceLabels:
                - __name__
              regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)
kubeProxy:
    # Disabled due to eBPF
    enabled: false
prometheus:
    ingress:
        enabled: true
        ingressClassName: traefik
        pathType: Prefix
        hosts:
            - prometheus.services.untouchedwagons.com
        tls:
            - hosts:
                - prometheus.services.untouchedwagons.com
    prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        enableAdminAPI: true
        walCompression: true
        retention: 7d
        retentionSize: 20GB
        storageSpec:
            volumeClaimTemplate:
                spec:
                    resources:
                        requests:
                            storage: 25Gi
defaultRules:
    rules:
        alertmanager: false
        general: false
        node: false
        nodeExporterRecording: false
        k8s: false
        kubeApiserverAvailability: false
        kubeApiserverBurnrate: false
        kubeApiserverHistogram: false
        kubeApiserverSlos: false
        kubeControllerManager: false
        kubePrometheusGeneral: false
        kubePrometheusNodeRecording: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        kubeStateMetrics: false
        kubelet: false
        kubernetesSystem: false
grafana:
    enabled: false
    forceDeployDashboards: true
    sidecar:
        dashboards:
            multicluster:
                etcd:
                    enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYk5Cd2ZJdHNEcnVwWTdZ
            UHZtUk52eUd6VWliNVJoT2FlVURxOEY1OEV3CjBaM3htc0w3eERnNjlCNEVCWnRO
            YW1FaXM1b3crU04yL3dYdlkwVVBqbmcKLS0tIGlMUk1QMUN5VHNrZFBUOGsrK3dW
            M211eCsrcWtaNEp3d0x1eXdHaG53d0EKtfbifPxrHnzz2C1hVDs8n3dH2SbxefZo
            vSSzdlHrGIF/e+FsC7LYj6qZX0T//F9mhbd8IFaNi1T+JCH0zojc1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T21:30:36Z"
    mac: ENC[AES256_GCM,data:KhsZ+FPcFbywivWOk06lJyuO+MCEbLhbs0OnwKPryogkMbQ3+OH2H+sm5gS57GFOM8fS2/Z2ogMNeMOmFvSGkzFlaxrfgJmz4pHEt0QMWKHQTYpaOIiKX2c0MX2UwxZA4War8d7w+zyOdU1xLz6+JSHC0ohxbfyrGLHaQJj2kUc=,iv:YNhHAatF9r8m+ssf13uAPaTLkbVY4xVv3IbHG8IKba0=,tag:Ya6r7AIHoet13bHmjfzoPg==,type:str]
    pgp: []
    encrypted_regex: ^(pushover_configs)$
    version: 3.8.0
