---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  annotations:
    enable.version-checker.io/main: "true"
    use-sha.version-checker.io/main: "false"
    use-metadata.version-checker.io/main: "true"

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.0.1
        args: 
          - sabnzbd
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          PORT: "9707"
          URL: "http://sabnzbd.default.svc.cluster.local:8080"
          APIKEY: "441c51b1799e551d7b4757b179fe7e96"

service:
  main:
    controller: main
    ports:
      http:
        port: 9707
    labels:
      instance: "exporter-sabnzbd.monitoring.svc.cluster.local"

serviceMonitor:
  main:
    enabled: true
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
    targetLabels:
      - instance
