---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flaresolverr
  namespace: servarr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.13
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          env:
            - name: TZ
              value: "America/Toronto"
            - name: PROMETHEUS_ENABLED
              value: "true"
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "1m"
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: servarr
spec:
  selector:
    app: flaresolverr
  ports:
    - name: http
      targetPort: 8191
      port: 8191
    - name: exporter
      targetPort: 8192
      port: 8192
