---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  annotations:
    enable.version-checker.io/main: "true"
    use-sha.version-checker.io/main: "false"
    use-metadata.version-checker.io/main: "true"

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.3.17
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        env:
          PROMETHEUS_ENABLED: "true"
          TZ: "America/Toronto"

service:
  main:
    controller: main
    ports:
      http:
        port: 8191
      exporter:
        port: 8192
